import type { Enchantment, EquipmentDefinition, LootTable } from './types';

// ===== Enchantment Definitions =====

export const ENCHANTMENTS: Record<string, Enchantment> = {
    auto_react: {
        type: 'auto_react',
        name: 'Auto React',
        nameJa: '自動反応',
        description: '10% chance to auto-trigger a random reaction on line clear',
        descriptionJa: 'ライン消去時10%の確率でランダムな反応を自動発動',
        color: '#FF6B6B',
    },
    orb_magnet: {
        type: 'orb_magnet',
        name: 'Orb Magnet',
        nameJa: 'オーブ磁石',
        description: 'Orbs are collected 50% faster',
        descriptionJa: 'オーブの回収速度が50%上昇',
        color: '#4FC3F7',
    },
    lucky_crit: {
        type: 'lucky_crit',
        name: 'Lucky Crit',
        nameJa: '幸運の一撃',
        description: '5% chance for 3x score on perfect beat',
        descriptionJa: 'パーフェクトビート時5%の確率でスコア3倍',
        color: '#FFD700',
    },
    terrain_shatter: {
        type: 'terrain_shatter',
        name: 'Terrain Shatter',
        nameJa: '地形粉砕',
        description: 'Line clears destroy +2 extra terrain blocks',
        descriptionJa: 'ライン消去時に追加で地形ブロック2個破壊',
        color: '#8D6E63',
    },
    combo_shield: {
        type: 'combo_shield',
        name: 'Combo Shield',
        nameJa: 'コンボシールド',
        description: 'First combo break per stage is ignored',
        descriptionJa: 'ステージごとに最初のコンボ途切れを無効化',
        color: '#42A5F5',
    },
    element_surge: {
        type: 'element_surge',
        name: 'Element Surge',
        nameJa: 'エレメントサージ',
        description: 'Reactions generate 1 extra orb of each consumed element',
        descriptionJa: '反応発動時、消費した各属性のオーブを1個追加生成',
        color: '#AB47BC',
    },
    material_convert: {
        type: 'material_convert',
        name: 'Material Convert',
        nameJa: '素材変換',
        description: '20% chance to upgrade material rarity on drop',
        descriptionJa: '素材ドロップ時20%の確率でレアリティが上昇',
        color: '#66BB6A',
    },
    beat_echo: {
        type: 'beat_echo',
        name: 'Beat Echo',
        nameJa: 'ビートエコー',
        description: 'PERFECT judgments count as 2 beats for gauge charging',
        descriptionJa: 'PERFECT判定がゲージチャージ用に2ビート分としてカウント',
        color: '#EF5350',
    },
};

/** All enchantments as a flat array */
export const ALL_ENCHANTMENTS: Enchantment[] = Object.values(ENCHANTMENTS);

/** All enchantment types for weighted random selection */
export const ALL_ENCHANTMENT_TYPES = ALL_ENCHANTMENTS.map(e => e.type);

// ===== Equipment Definitions =====

const EQUIPMENT: EquipmentDefinition[] = [
    // ── Weapons (offense) ─────────────────────────────────────────
    {
        id: 'wooden_baton',
        name: 'Wooden Baton',
        nameJa: '木のバトン',
        slot: 'weapon',
        rarity: 'common',
        icon: '🪵',
        color: '#8B6914',
        glowColor: '#A0822B',
        description: 'A simple baton carved from driftwood. Keeps the rhythm going.',
        descriptionJa: '流木を削って作った素朴なバトン。リズムを刻み続ける。',
        baseStats: [{ stat: 'scorePercent', value: 5 }],
        enchantmentSlots: 0,
    },
    {
        id: 'crystal_wand',
        name: 'Crystal Wand',
        nameJa: 'クリスタルワンド',
        slot: 'weapon',
        rarity: 'uncommon',
        icon: '🔮',
        color: '#4FC3F7',
        glowColor: '#81D4FA',
        description: 'A wand tipped with a resonating crystal that amplifies rhythmic energy.',
        descriptionJa: '共鳴する水晶が先端に付いた杖。リズムエネルギーを増幅する。',
        baseStats: [
            { stat: 'scorePercent', value: 10 },
            { stat: 'elementalAffinity', value: 5, element: 'water' },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'flame_striker',
        name: 'Flame Striker',
        nameJa: 'フレイムストライカー',
        slot: 'weapon',
        rarity: 'rare',
        icon: '🔥',
        color: '#FF4444',
        glowColor: '#FF8866',
        description: 'A blazing conductor\'s baton wreathed in eternal fire.',
        descriptionJa: '永遠の炎に包まれた指揮棒。',
        baseStats: [
            { stat: 'scorePercent', value: 15 },
            { stat: 'elementalAffinity', value: 10, element: 'fire' },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'thunder_gavel',
        name: 'Thunder Gavel',
        nameJa: 'サンダーガベル',
        slot: 'weapon',
        rarity: 'epic',
        icon: '⚡',
        color: '#FFDD44',
        glowColor: '#FFEE88',
        description: 'A gavel forged from thunderstone. Each strike resonates with the storm.',
        descriptionJa: '雷石で鍛造された槌。一撃ごとに嵐が共鳴する。',
        baseStats: [
            { stat: 'scorePercent', value: 25 },
            { stat: 'elementalAffinity', value: 15, element: 'lightning' },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'star_conductor_baton',
        name: 'Star Conductor\'s Baton',
        nameJa: '星の指揮棒',
        slot: 'weapon',
        rarity: 'legendary',
        icon: '✨',
        color: '#FFFFFF',
        glowColor: '#F0F0FF',
        description: 'The baton of the celestial orchestra. Commands all elements in harmony.',
        descriptionJa: '天球のオーケストラの指揮棒。全属性を調和のうちに統べる。',
        baseStats: [
            { stat: 'scorePercent', value: 40 },
            { stat: 'elementalAffinity', value: 20, element: 'fire' },
            { stat: 'elementalAffinity', value: 20, element: 'water' },
            { stat: 'elementalAffinity', value: 20, element: 'ice' },
            { stat: 'elementalAffinity', value: 20, element: 'lightning' },
            { stat: 'elementalAffinity', value: 20, element: 'nature' },
            { stat: 'elementalAffinity', value: 20, element: 'dark' },
        ],
        enchantmentSlots: 2,
    },
    {
        id: 'dark_requiem',
        name: 'Dark Requiem',
        nameJa: 'ダークレクイエム',
        slot: 'weapon',
        rarity: 'rare',
        icon: '🌑',
        color: '#9944CC',
        glowColor: '#BB66EE',
        description: 'A shadowy baton that draws power from the void between beats.',
        descriptionJa: 'ビートの間の虚無から力を引き出す影のバトン。',
        baseStats: [
            { stat: 'scorePercent', value: 12 },
            { stat: 'elementalAffinity', value: 15, element: 'dark' },
            { stat: 'reactionPower', value: 8 },
        ],
        enchantmentSlots: 0,
    },

    // ── Armor (defense) ───────────────────────────────────────────
    {
        id: 'cloth_robe',
        name: 'Cloth Robe',
        nameJa: '布のローブ',
        slot: 'armor',
        rarity: 'common',
        icon: '👘',
        color: '#8B8B8B',
        glowColor: '#A0A0A0',
        description: 'A simple cloth robe. Offers minimal protection but keeps you moving.',
        descriptionJa: 'シンプルな布のローブ。最低限の守りだが動きやすい。',
        baseStats: [{ stat: 'comboDuration', value: 50 }],
        enchantmentSlots: 0,
    },
    {
        id: 'iron_vest',
        name: 'Iron Vest',
        nameJa: 'アイアンベスト',
        slot: 'armor',
        rarity: 'uncommon',
        icon: '🦺',
        color: '#B87333',
        glowColor: '#D4956B',
        description: 'A sturdy vest reinforced with iron plates. Slows gravity slightly.',
        descriptionJa: '鉄板で補強された頑丈なベスト。重力がわずかに軽減される。',
        baseStats: [
            { stat: 'comboDuration', value: 100 },
            { stat: 'gravityReduce', value: 3 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'crystal_mail',
        name: 'Crystal Mail',
        nameJa: 'クリスタルメイル',
        slot: 'armor',
        rarity: 'rare',
        icon: '💎',
        color: '#4FC3F7',
        glowColor: '#81D4FA',
        description: 'Armor woven from crystallized rhythm. Resonates with every beat.',
        descriptionJa: '結晶化したリズムで編まれた鎧。ビートごとに共鳴する。',
        baseStats: [
            { stat: 'comboDuration', value: 150 },
            { stat: 'gravityReduce', value: 5 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'obsidian_plate',
        name: 'Obsidian Plate',
        nameJa: 'オブシディアンプレート',
        slot: 'armor',
        rarity: 'epic',
        icon: '🪨',
        color: '#9C27B0',
        glowColor: '#CE93D8',
        description: 'Plate armor of volcanic obsidian. Dark energy cushions every impact.',
        descriptionJa: '火山の黒曜石で作られたプレートアーマー。暗黒エネルギーが衝撃を吸収。',
        baseStats: [
            { stat: 'comboDuration', value: 200 },
            { stat: 'gravityReduce', value: 8 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'star_aegis',
        name: 'Star Aegis',
        nameJa: '星盾の鎧',
        slot: 'armor',
        rarity: 'legendary',
        icon: '🌟',
        color: '#FFFFFF',
        glowColor: '#F0F0FF',
        description: 'Celestial armor forged from starlight. Gravity itself bends around the wearer.',
        descriptionJa: '星光から鍛造された天球の鎧。重力すら装着者の周りで歪む。',
        baseStats: [
            { stat: 'comboDuration', value: 300 },
            { stat: 'gravityReduce', value: 15 },
        ],
        enchantmentSlots: 2,
    },
    {
        id: 'nature_weave',
        name: 'Nature Weave',
        nameJa: 'ネイチャーウィーブ',
        slot: 'armor',
        rarity: 'rare',
        icon: '🌿',
        color: '#44CC44',
        glowColor: '#66EE66',
        description: 'Living vines form a protective shell that regenerates with nature\'s pulse.',
        descriptionJa: '生きた蔓が自然の脈動と共に再生する防護殻を形成する。',
        baseStats: [
            { stat: 'comboDuration', value: 120 },
            { stat: 'gravityReduce', value: 4 },
            { stat: 'elementalAffinity', value: 10, element: 'nature' },
        ],
        enchantmentSlots: 0,
    },

    // ── Accessories (utility) ─────────────────────────────────────
    {
        id: 'wooden_ring',
        name: 'Wooden Ring',
        nameJa: '木のリング',
        slot: 'accessory',
        rarity: 'common',
        icon: '💍',
        color: '#8B6914',
        glowColor: '#A0822B',
        description: 'A simple wooden ring. Slightly widens the beat timing window.',
        descriptionJa: 'シンプルな木のリング。ビートの判定窓がわずかに広がる。',
        baseStats: [{ stat: 'beatWindow', value: 3 }],
        enchantmentSlots: 0,
    },
    {
        id: 'silver_band',
        name: 'Silver Band',
        nameJa: 'シルバーバンド',
        slot: 'accessory',
        rarity: 'uncommon',
        icon: '🪙',
        color: '#C0C0C0',
        glowColor: '#E0E0E0',
        description: 'A polished silver band that attunes to fortune\'s flow.',
        descriptionJa: '磨き上げた銀の腕輪。幸運の流れに調律される。',
        baseStats: [
            { stat: 'beatWindow', value: 5 },
            { stat: 'dropRate', value: 5 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'gold_monocle',
        name: 'Gold Monocle',
        nameJa: 'ゴールドモノクル',
        slot: 'accessory',
        rarity: 'rare',
        icon: '🧐',
        color: '#FFD700',
        glowColor: '#FFECB3',
        description: 'A golden monocle that reveals hidden treasures and sharpens timing.',
        descriptionJa: '隠された宝を見抜き、タイミングを研ぎ澄ます金のモノクル。',
        baseStats: [
            { stat: 'beatWindow', value: 8 },
            { stat: 'dropRate', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'prismatic_lens',
        name: 'Prismatic Lens',
        nameJa: 'プリズマティックレンズ',
        slot: 'accessory',
        rarity: 'epic',
        icon: '🔬',
        color: '#9C27B0',
        glowColor: '#CE93D8',
        description: 'A lens that splits light into seven colors, each attuned to a different frequency.',
        descriptionJa: '光を七色に分解するレンズ。それぞれが異なる周波数に調律されている。',
        baseStats: [
            { stat: 'beatWindow', value: 12 },
            { stat: 'dropRate', value: 15 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'celestial_crown',
        name: 'Celestial Crown',
        nameJa: '天球の冠',
        slot: 'accessory',
        rarity: 'legendary',
        icon: '👑',
        color: '#FFFFFF',
        glowColor: '#F0F0FF',
        description: 'A crown woven from starlight threads. The universe bends to its wearer\'s will.',
        descriptionJa: '星光の糸で編まれた冠。宇宙が装着者の意志に従う。',
        baseStats: [
            { stat: 'beatWindow', value: 18 },
            { stat: 'dropRate', value: 25 },
        ],
        enchantmentSlots: 2,
    },
    {
        id: 'combo_bracelet',
        name: 'Combo Bracelet',
        nameJa: 'コンボブレスレット',
        slot: 'accessory',
        rarity: 'rare',
        icon: '📿',
        color: '#FF7043',
        glowColor: '#FFAB91',
        description: 'A bracelet with chained links that resonate with each successive hit.',
        descriptionJa: '連続する打撃に共鳴する鎖のブレスレット。',
        baseStats: [
            { stat: 'beatWindow', value: 5 },
            { stat: 'comboAmplify', value: 12 },
        ],
        enchantmentSlots: 0,
    },

    // ── Charms (elemental) ────────────────────────────────────────
    {
        id: 'charm_fire',
        name: 'Ember Charm',
        nameJa: '残り火のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '🔥',
        color: '#FF4444',
        glowColor: '#FF8866',
        description: 'A warm charm that pulses with inner flame. Fire orbs appear more often.',
        descriptionJa: '内なる炎で脈動する温かいお守り。炎オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'fire' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_water',
        name: 'Tide Charm',
        nameJa: '潮のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '💧',
        color: '#4488FF',
        glowColor: '#66AAFF',
        description: 'A cool charm that ebbs and flows like the ocean. Water orbs appear more often.',
        descriptionJa: '海のように満ち引きする冷たいお守り。水オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'water' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_ice',
        name: 'Frost Charm',
        nameJa: '霜のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '❄️',
        color: '#88DDFF',
        glowColor: '#BBEEFF',
        description: 'A frigid charm coated in eternal frost. Ice orbs appear more often.',
        descriptionJa: '永遠の霜に覆われた極寒のお守り。氷オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'ice' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_lightning',
        name: 'Spark Charm',
        nameJa: '閃光のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '⚡',
        color: '#FFDD44',
        glowColor: '#FFEE88',
        description: 'A crackling charm that arcs with static. Lightning orbs appear more often.',
        descriptionJa: '静電気が走る弾けるお守り。雷オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'lightning' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_nature',
        name: 'Bloom Charm',
        nameJa: '花咲のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '🌿',
        color: '#44CC44',
        glowColor: '#66EE66',
        description: 'A living charm that sprouts tiny flowers. Nature orbs appear more often.',
        descriptionJa: '小さな花が咲く生きたお守り。自然オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'nature' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_dark',
        name: 'Void Charm',
        nameJa: '虚無のお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '🌑',
        color: '#9944CC',
        glowColor: '#BB66EE',
        description: 'A charm that absorbs light around it. Dark orbs appear more often.',
        descriptionJa: '周囲の光を吸収するお守り。闇オーブの出現率が上昇。',
        baseStats: [
            { stat: 'elementalAffinity', value: 15, element: 'dark' },
            { stat: 'reactionPower', value: 10 },
        ],
        enchantmentSlots: 0,
    },
    {
        id: 'charm_vaporize',
        name: 'Steam Core Charm',
        nameJa: '蒸気核のお守り',
        slot: 'charm',
        rarity: 'epic',
        icon: '💨',
        color: '#FF8844',
        glowColor: '#FFAA66',
        description: 'A charm forged where fire meets water. Amplifies Vaporize reactions.',
        descriptionJa: '炎と水が出会う場所で鍛えられたお守り。蒸発反応を強化。',
        baseStats: [
            { stat: 'elementalAffinity', value: 12, element: 'fire' },
            { stat: 'elementalAffinity', value: 12, element: 'water' },
            { stat: 'reactionPower', value: 18 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'charm_superconduct',
        name: 'Tempest Core Charm',
        nameJa: '嵐核のお守り',
        slot: 'charm',
        rarity: 'epic',
        icon: '🌩️',
        color: '#88BBFF',
        glowColor: '#AADDFF',
        description: 'A charm vibrating at the frequency of ice and lightning. Amplifies Superconduct reactions.',
        descriptionJa: '氷と雷の周波数で振動するお守り。超電導反応を強化。',
        baseStats: [
            { stat: 'elementalAffinity', value: 12, element: 'ice' },
            { stat: 'elementalAffinity', value: 12, element: 'lightning' },
            { stat: 'reactionPower', value: 18 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'charm_bloom_nature',
        name: 'Genesis Bloom Charm',
        nameJa: '創生花のお守り',
        slot: 'charm',
        rarity: 'epic',
        icon: '🌸',
        color: '#44CC88',
        glowColor: '#66EEAA',
        description: 'A charm woven from primal vines and dewdrops. Amplifies Bloom reactions.',
        descriptionJa: '原始の蔓と朝露で編まれたお守り。開花反応を強化。',
        baseStats: [
            { stat: 'elementalAffinity', value: 12, element: 'nature' },
            { stat: 'elementalAffinity', value: 12, element: 'water' },
            { stat: 'reactionPower', value: 18 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'charm_omniscient',
        name: 'Omniscient Talisman',
        nameJa: '全知の護符',
        slot: 'charm',
        rarity: 'legendary',
        icon: '🌀',
        color: '#FFFFFF',
        glowColor: '#F0F0FF',
        description: 'A talisman that resonates with every element. The pinnacle of elemental mastery.',
        descriptionJa: '全属性に共鳴する護符。属性支配の頂点。',
        baseStats: [
            { stat: 'elementalAffinity', value: 10, element: 'fire' },
            { stat: 'elementalAffinity', value: 10, element: 'water' },
            { stat: 'elementalAffinity', value: 10, element: 'ice' },
            { stat: 'elementalAffinity', value: 10, element: 'lightning' },
            { stat: 'elementalAffinity', value: 10, element: 'nature' },
            { stat: 'elementalAffinity', value: 10, element: 'dark' },
            { stat: 'reactionPower', value: 25 },
        ],
        enchantmentSlots: 2,
    },
    {
        id: 'charm_terrain',
        name: 'Earthshaker Pendant',
        nameJa: '地震のペンダント',
        slot: 'charm',
        rarity: 'epic',
        icon: '⛰️',
        color: '#8D6E63',
        glowColor: '#BCAAA4',
        description: 'A heavy pendant that channels seismic energy into devastating terrain strikes.',
        descriptionJa: '地震のエネルギーを地形への破壊的一撃に変換する重いペンダント。',
        baseStats: [
            { stat: 'terrainDamage', value: 20 },
            { stat: 'reactionPower', value: 12 },
        ],
        enchantmentSlots: 1,
    },
    {
        id: 'charm_combo',
        name: 'Rhythm Heart Charm',
        nameJa: 'リズムハートのお守り',
        slot: 'charm',
        rarity: 'rare',
        icon: '💗',
        color: '#EF5350',
        glowColor: '#EF9A9A',
        description: 'A charm that beats in time with the music. Combos grow stronger.',
        descriptionJa: '音楽と同じリズムで鼓動するお守り。コンボがより強力に成長。',
        baseStats: [
            { stat: 'comboAmplify', value: 15 },
            { stat: 'comboDuration', value: 80 },
        ],
        enchantmentSlots: 0,
    },
];

// ===== Registry Lookups =====

/** All equipment definitions indexed by ID. */
export const EQUIPMENT_REGISTRY: Record<string, EquipmentDefinition> = Object.fromEntries(
    EQUIPMENT.map(eq => [eq.id, eq])
);

/** Get an equipment definition by ID, or undefined if not found. */
export function getEquipment(id: string): EquipmentDefinition | undefined {
    return EQUIPMENT_REGISTRY[id];
}

/** All equipment as a flat array. */
export const ALL_EQUIPMENT = EQUIPMENT;

/** Equipment grouped by slot. */
export const EQUIPMENT_BY_SLOT: Record<string, EquipmentDefinition[]> = {
    weapon: EQUIPMENT.filter(e => e.slot === 'weapon'),
    armor: EQUIPMENT.filter(e => e.slot === 'armor'),
    accessory: EQUIPMENT.filter(e => e.slot === 'accessory'),
    charm: EQUIPMENT.filter(e => e.slot === 'charm'),
};

// ===== Loot Tables (one per world) =====

export const LOOT_TABLES: LootTable[] = [
    // World 1: Heavily weighted toward common/uncommon
    {
        worldIdx: 0,
        lineCountBonus: 0.01,
        comboBonus: 0.005,
        entries: [
            // Common (50%)
            { equipmentId: 'wooden_baton', weight: 12 },
            { equipmentId: 'cloth_robe', weight: 13 },
            { equipmentId: 'wooden_ring', weight: 13 },
            { equipmentId: 'charm_combo', weight: 12 },
            // Uncommon (35%)
            { equipmentId: 'crystal_wand', weight: 12 },
            { equipmentId: 'iron_vest', weight: 12 },
            { equipmentId: 'silver_band', weight: 11 },
            // Rare (12%)
            { equipmentId: 'flame_striker', weight: 2 },
            { equipmentId: 'crystal_mail', weight: 2 },
            { equipmentId: 'gold_monocle', weight: 2 },
            { equipmentId: 'charm_fire', weight: 1.5 },
            { equipmentId: 'charm_water', weight: 1.5 },
            { equipmentId: 'charm_ice', weight: 1.5 },
            { equipmentId: 'charm_lightning', weight: 1.5 },
            // Epic (2.5%)
            { equipmentId: 'thunder_gavel', weight: 0.5 },
            { equipmentId: 'obsidian_plate', weight: 0.5 },
            { equipmentId: 'prismatic_lens', weight: 0.5 },
            { equipmentId: 'charm_vaporize', weight: 0.5 },
            { equipmentId: 'charm_terrain', weight: 0.5 },
            // Legendary (0.5%)
            { equipmentId: 'star_conductor_baton', weight: 0.1 },
            { equipmentId: 'star_aegis', weight: 0.1 },
            { equipmentId: 'celestial_crown', weight: 0.1 },
            { equipmentId: 'charm_omniscient', weight: 0.2 },
        ],
    },
    // World 2: Slightly better odds
    {
        worldIdx: 1,
        lineCountBonus: 0.012,
        comboBonus: 0.006,
        entries: [
            // Common (40%)
            { equipmentId: 'wooden_baton', weight: 10 },
            { equipmentId: 'cloth_robe', weight: 10 },
            { equipmentId: 'wooden_ring', weight: 10 },
            { equipmentId: 'charm_combo', weight: 10 },
            // Uncommon (35%)
            { equipmentId: 'crystal_wand', weight: 12 },
            { equipmentId: 'iron_vest', weight: 12 },
            { equipmentId: 'silver_band', weight: 11 },
            // Rare (18%)
            { equipmentId: 'flame_striker', weight: 3 },
            { equipmentId: 'crystal_mail', weight: 3 },
            { equipmentId: 'gold_monocle', weight: 3 },
            { equipmentId: 'dark_requiem', weight: 2 },
            { equipmentId: 'nature_weave', weight: 2 },
            { equipmentId: 'combo_bracelet', weight: 2 },
            { equipmentId: 'charm_fire', weight: 0.5 },
            { equipmentId: 'charm_water', weight: 0.5 },
            { equipmentId: 'charm_nature', weight: 0.5 },
            { equipmentId: 'charm_dark', weight: 0.5 },
            // Epic (5%)
            { equipmentId: 'thunder_gavel', weight: 1 },
            { equipmentId: 'obsidian_plate', weight: 1 },
            { equipmentId: 'prismatic_lens', weight: 1 },
            { equipmentId: 'charm_vaporize', weight: 1 },
            { equipmentId: 'charm_terrain', weight: 1 },
            // Legendary (2%)
            { equipmentId: 'star_conductor_baton', weight: 0.5 },
            { equipmentId: 'star_aegis', weight: 0.5 },
            { equipmentId: 'celestial_crown', weight: 0.5 },
            { equipmentId: 'charm_omniscient', weight: 0.5 },
        ],
    },
    // World 3: Balanced mid-game
    {
        worldIdx: 2,
        lineCountBonus: 0.015,
        comboBonus: 0.007,
        entries: [
            // Common (30%)
            { equipmentId: 'wooden_baton', weight: 7 },
            { equipmentId: 'cloth_robe', weight: 8 },
            { equipmentId: 'wooden_ring', weight: 8 },
            { equipmentId: 'charm_combo', weight: 7 },
            // Uncommon (30%)
            { equipmentId: 'crystal_wand', weight: 10 },
            { equipmentId: 'iron_vest', weight: 10 },
            { equipmentId: 'silver_band', weight: 10 },
            // Rare (25%)
            { equipmentId: 'flame_striker', weight: 3 },
            { equipmentId: 'crystal_mail', weight: 3 },
            { equipmentId: 'gold_monocle', weight: 3 },
            { equipmentId: 'dark_requiem', weight: 2 },
            { equipmentId: 'nature_weave', weight: 2 },
            { equipmentId: 'combo_bracelet', weight: 2 },
            { equipmentId: 'charm_fire', weight: 1.5 },
            { equipmentId: 'charm_water', weight: 1.5 },
            { equipmentId: 'charm_ice', weight: 1.5 },
            { equipmentId: 'charm_lightning', weight: 1.5 },
            { equipmentId: 'charm_nature', weight: 1.5 },
            { equipmentId: 'charm_dark', weight: 1.5 },
            // Epic (10%)
            { equipmentId: 'thunder_gavel', weight: 1.5 },
            { equipmentId: 'obsidian_plate', weight: 1.5 },
            { equipmentId: 'prismatic_lens', weight: 1.5 },
            { equipmentId: 'charm_vaporize', weight: 1.5 },
            { equipmentId: 'charm_superconduct', weight: 1.5 },
            { equipmentId: 'charm_bloom_nature', weight: 1.5 },
            { equipmentId: 'charm_terrain', weight: 1 },
            // Legendary (5%)
            { equipmentId: 'star_conductor_baton', weight: 1.25 },
            { equipmentId: 'star_aegis', weight: 1.25 },
            { equipmentId: 'celestial_crown', weight: 1.25 },
            { equipmentId: 'charm_omniscient', weight: 1.25 },
        ],
    },
    // World 4: Skewed toward higher rarity
    {
        worldIdx: 3,
        lineCountBonus: 0.018,
        comboBonus: 0.008,
        entries: [
            // Common (25%)
            { equipmentId: 'wooden_baton', weight: 6 },
            { equipmentId: 'cloth_robe', weight: 6 },
            { equipmentId: 'wooden_ring', weight: 7 },
            { equipmentId: 'charm_combo', weight: 6 },
            // Uncommon (28%)
            { equipmentId: 'crystal_wand', weight: 9 },
            { equipmentId: 'iron_vest', weight: 9 },
            { equipmentId: 'silver_band', weight: 10 },
            // Rare (27%)
            { equipmentId: 'flame_striker', weight: 3 },
            { equipmentId: 'crystal_mail', weight: 3 },
            { equipmentId: 'gold_monocle', weight: 3 },
            { equipmentId: 'dark_requiem', weight: 3 },
            { equipmentId: 'nature_weave', weight: 3 },
            { equipmentId: 'combo_bracelet', weight: 3 },
            { equipmentId: 'charm_fire', weight: 1.5 },
            { equipmentId: 'charm_water', weight: 1.5 },
            { equipmentId: 'charm_ice', weight: 1.5 },
            { equipmentId: 'charm_lightning', weight: 1.5 },
            { equipmentId: 'charm_nature', weight: 1.5 },
            { equipmentId: 'charm_dark', weight: 1.5 },
            // Epic (13%)
            { equipmentId: 'thunder_gavel', weight: 2 },
            { equipmentId: 'obsidian_plate', weight: 2 },
            { equipmentId: 'prismatic_lens', weight: 2 },
            { equipmentId: 'charm_vaporize', weight: 1.5 },
            { equipmentId: 'charm_superconduct', weight: 1.5 },
            { equipmentId: 'charm_bloom_nature', weight: 1.5 },
            { equipmentId: 'charm_terrain', weight: 2.5 },
            // Legendary (7%)
            { equipmentId: 'star_conductor_baton', weight: 1.75 },
            { equipmentId: 'star_aegis', weight: 1.75 },
            { equipmentId: 'celestial_crown', weight: 1.75 },
            { equipmentId: 'charm_omniscient', weight: 1.75 },
        ],
    },
    // World 5: Best drops — fewer commons, many rares and epics
    {
        worldIdx: 4,
        lineCountBonus: 0.02,
        comboBonus: 0.01,
        entries: [
            // Common (20%)
            { equipmentId: 'wooden_baton', weight: 5 },
            { equipmentId: 'cloth_robe', weight: 5 },
            { equipmentId: 'wooden_ring', weight: 5 },
            { equipmentId: 'charm_combo', weight: 5 },
            // Uncommon (20%)
            { equipmentId: 'crystal_wand', weight: 7 },
            { equipmentId: 'iron_vest', weight: 7 },
            { equipmentId: 'silver_band', weight: 6 },
            // Rare (30%)
            { equipmentId: 'flame_striker', weight: 3.5 },
            { equipmentId: 'crystal_mail', weight: 3.5 },
            { equipmentId: 'gold_monocle', weight: 3.5 },
            { equipmentId: 'dark_requiem', weight: 3 },
            { equipmentId: 'nature_weave', weight: 3 },
            { equipmentId: 'combo_bracelet', weight: 3 },
            { equipmentId: 'charm_fire', weight: 1.75 },
            { equipmentId: 'charm_water', weight: 1.75 },
            { equipmentId: 'charm_ice', weight: 1.75 },
            { equipmentId: 'charm_lightning', weight: 1.75 },
            { equipmentId: 'charm_nature', weight: 1.75 },
            { equipmentId: 'charm_dark', weight: 1.75 },
            // Epic (15%)
            { equipmentId: 'thunder_gavel', weight: 2.5 },
            { equipmentId: 'obsidian_plate', weight: 2.5 },
            { equipmentId: 'prismatic_lens', weight: 2.5 },
            { equipmentId: 'charm_vaporize', weight: 2 },
            { equipmentId: 'charm_superconduct', weight: 2 },
            { equipmentId: 'charm_bloom_nature', weight: 2 },
            { equipmentId: 'charm_terrain', weight: 1.5 },
            // Legendary (5%)  (relative to total — higher absolute)
            { equipmentId: 'star_conductor_baton', weight: 1.25 },
            { equipmentId: 'star_aegis', weight: 1.25 },
            { equipmentId: 'celestial_crown', weight: 1.25 },
            { equipmentId: 'charm_omniscient', weight: 1.25 },
        ],
    },
];

/** Get loot table for a world, falling back to last table for higher worlds. */
export function getLootTable(worldIdx: number): LootTable {
    if (worldIdx < 0) return LOOT_TABLES[0];
    if (worldIdx >= LOOT_TABLES.length) return LOOT_TABLES[LOOT_TABLES.length - 1];
    return LOOT_TABLES[worldIdx];
}
