// =============================================================================
// Minecraft: Nintendo Switch Edition — Functional, Redstone, Transport & Food
// =============================================================================
// Functional blocks (crafting table, furnace, chest, enchanting table, etc.),
// redstone components (pistons, repeaters, comparators, etc.), transportation
// (rails, minecarts, boats, saddle), and food recipes.
// =============================================================================

import type { CraftingRecipe } from '@/types/minecraft-switch';

export const FUNCTIONAL_RECIPES: CraftingRecipe[] = [

  // ===========================================================================
  // FUNCTIONAL BLOCKS
  // ===========================================================================

  {
    id: 'crafting_table',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'oak_planks' },
    result: 'crafting_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'furnace',
    type: 'shaped',
    pattern: ['###', '# #', '###'],
    key: { '#': 'cobblestone' },
    result: 'furnace',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'blast_furnace',
    type: 'shaped',
    pattern: ['III', 'IFI', 'SSS'],
    key: { 'I': 'iron_ingot', 'F': 'furnace', 'S': 'smooth_stone' },
    result: 'blast_furnace',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'smoker',
    type: 'shaped',
    pattern: [' L ', 'LFL', ' L '],
    key: { 'L': 'oak_log', 'F': 'furnace' },
    result: 'smoker',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'chest',
    type: 'shaped',
    pattern: ['###', '# #', '###'],
    key: { '#': 'oak_planks' },
    result: 'chest',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'trapped_chest',
    type: 'shapeless',
    ingredients: ['chest', 'tripwire_hook'],
    result: 'trapped_chest',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'ender_chest',
    type: 'shaped',
    pattern: ['OOO', 'OEO', 'OOO'],
    key: { 'O': 'obsidian', 'E': 'ender_eye' },
    result: 'ender_chest',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'barrel',
    type: 'shaped',
    pattern: ['#S#', '# #', '#S#'],
    key: { '#': 'oak_planks', 'S': 'oak_slab' },
    result: 'barrel',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'enchanting_table',
    type: 'shaped',
    pattern: [' B ', 'DOD', 'OOO'],
    key: { 'B': 'book', 'D': 'diamond', 'O': 'obsidian' },
    result: 'enchanting_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'brewing_stand',
    type: 'shaped',
    pattern: [' R ', 'SSS'],
    key: { 'R': 'blaze_rod', 'S': 'cobblestone' },
    result: 'brewing_stand',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'anvil',
    type: 'shaped',
    pattern: ['BBB', ' I ', 'III'],
    key: { 'B': 'iron_block', 'I': 'iron_ingot' },
    result: 'anvil',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'beacon',
    type: 'shaped',
    pattern: ['GGG', 'GNG', 'OOO'],
    key: { 'G': 'glass', 'N': 'nether_star', 'O': 'obsidian' },
    result: 'beacon',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'grindstone',
    type: 'shaped',
    pattern: ['|S|', '# #'],
    key: { '|': 'stick', 'S': 'stone_slab', '#': 'oak_planks' },
    result: 'grindstone',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'stonecutter',
    type: 'shaped',
    pattern: [' I ', 'SSS'],
    key: { 'I': 'iron_ingot', 'S': 'stone' },
    result: 'stonecutter',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'loom',
    type: 'shaped',
    pattern: ['SS', '##'],
    key: { 'S': 'string', '#': 'oak_planks' },
    result: 'loom',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'cartography_table',
    type: 'shaped',
    pattern: ['PP', '##', '##'],
    key: { 'P': 'paper', '#': 'oak_planks' },
    result: 'cartography_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'fletching_table',
    type: 'shaped',
    pattern: ['FF', '##', '##'],
    key: { 'F': 'flint', '#': 'oak_planks' },
    result: 'fletching_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'smithing_table',
    type: 'shaped',
    pattern: ['II', '##', '##'],
    key: { 'I': 'iron_ingot', '#': 'oak_planks' },
    result: 'smithing_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'composter',
    type: 'shaped',
    pattern: ['# #', '# #', '###'],
    key: { '#': 'oak_slab' },
    result: 'composter',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'cauldron',
    type: 'shaped',
    pattern: ['# #', '# #', '###'],
    key: { '#': 'iron_ingot' },
    result: 'cauldron',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'jukebox',
    type: 'shaped',
    pattern: ['###', '#D#', '###'],
    key: { '#': 'oak_planks', 'D': 'diamond' },
    result: 'jukebox',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'note_block',
    type: 'shaped',
    pattern: ['###', '#R#', '###'],
    key: { '#': 'oak_planks', 'R': 'redstone' },
    result: 'note_block',
    resultCount: 1,
    category: 'redstone',
  },

  // ===========================================================================
  // REDSTONE
  // ===========================================================================

  {
    id: 'redstone_torch',
    type: 'shaped',
    pattern: ['R', '|'],
    key: { 'R': 'redstone', '|': 'stick' },
    result: 'redstone_torch',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_repeater',
    type: 'shaped',
    pattern: ['TRT', 'SSS'],
    key: { 'T': 'redstone_torch', 'R': 'redstone', 'S': 'stone' },
    result: 'redstone_repeater',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_comparator',
    type: 'shaped',
    pattern: [' T ', 'TQT', 'SSS'],
    key: { 'T': 'redstone_torch', 'Q': 'nether_quartz', 'S': 'stone' },
    result: 'redstone_comparator',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'piston',
    type: 'shaped',
    pattern: ['###', 'CIC', 'CRC'],
    key: { '#': 'oak_planks', 'C': 'cobblestone', 'I': 'iron_ingot', 'R': 'redstone' },
    result: 'piston',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'sticky_piston',
    type: 'shaped',
    pattern: ['S', 'P'],
    key: { 'S': 'slime_ball', 'P': 'piston' },
    result: 'sticky_piston',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'observer',
    type: 'shaped',
    pattern: ['CCC', 'RRQ', 'CCC'],
    key: { 'C': 'cobblestone', 'R': 'redstone', 'Q': 'nether_quartz' },
    result: 'observer',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'dropper',
    type: 'shaped',
    pattern: ['CCC', 'C C', 'CRC'],
    key: { 'C': 'cobblestone', 'R': 'redstone' },
    result: 'dropper',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'dispenser',
    type: 'shaped',
    pattern: ['CCC', 'CBC', 'CRC'],
    key: { 'C': 'cobblestone', 'B': 'bow', 'R': 'redstone' },
    result: 'dispenser',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'hopper',
    type: 'shaped',
    pattern: ['I I', 'ICI', ' I '],
    key: { 'I': 'iron_ingot', 'C': 'chest' },
    result: 'hopper',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'tnt',
    type: 'shaped',
    pattern: ['GSG', 'SGS', 'GSG'],
    key: { 'G': 'gunpowder', 'S': 'sand' },
    result: 'tnt',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'tripwire_hook',
    type: 'shaped',
    pattern: ['I', '|', '#'],
    key: { 'I': 'iron_ingot', '|': 'stick', '#': 'oak_planks' },
    result: 'tripwire_hook',
    resultCount: 2,
    category: 'redstone',
  },
  {
    id: 'target',
    type: 'shaped',
    pattern: [' R ', 'RHR', ' R '],
    key: { 'R': 'redstone', 'H': 'hay_bale' },
    result: 'target',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'lever',
    type: 'shaped',
    pattern: ['|', '#'],
    key: { '|': 'stick', '#': 'cobblestone' },
    result: 'lever',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'daylight_detector',
    type: 'shaped',
    pattern: ['GGG', 'QQQ', 'SSS'],
    key: { 'G': 'glass', 'Q': 'nether_quartz', 'S': 'oak_slab' },
    result: 'daylight_detector',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_lamp',
    type: 'shaped',
    pattern: [' R ', 'RGR', ' R '],
    key: { 'R': 'redstone', 'G': 'glowstone' },
    result: 'redstone_lamp',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'slime_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'slime_ball' },
    result: 'slime_block',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'honey_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'honey_bottle' },
    result: 'honey_block',
    resultCount: 1,
    category: 'redstone',
  },

  // ===========================================================================
  // TRANSPORTATION
  // ===========================================================================

  {
    id: 'rail',
    type: 'shaped',
    pattern: ['I I', 'I|I', 'I I'],
    key: { 'I': 'iron_ingot', '|': 'stick' },
    result: 'rail',
    resultCount: 16,
    category: 'transportation',
  },
  {
    id: 'powered_rail',
    type: 'shaped',
    pattern: ['G G', 'G|G', 'GRG'],
    key: { 'G': 'gold_ingot', '|': 'stick', 'R': 'redstone' },
    result: 'powered_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'detector_rail',
    type: 'shaped',
    pattern: ['I I', 'ISI', 'IRI'],
    key: { 'I': 'iron_ingot', 'S': 'stone_pressure_plate', 'R': 'redstone' },
    result: 'detector_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'activator_rail',
    type: 'shaped',
    pattern: ['ISI', 'I|I', 'ISI'],
    key: { 'I': 'iron_ingot', 'S': 'stick', '|': 'redstone_torch' },
    result: 'activator_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'minecart',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'iron_ingot' },
    result: 'minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'chest_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'chest'],
    result: 'chest_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'furnace_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'furnace'],
    result: 'furnace_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'hopper_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'hopper'],
    result: 'hopper_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'tnt_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'tnt'],
    result: 'tnt_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'oak_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'spruce_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'birch_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'birch_planks' },
    result: 'birch_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'jungle_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'acacia_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'dark_oak_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'saddle_from_leather',
    type: 'shaped',
    pattern: ['LLL', 'L L'],
    key: { 'L': 'leather' },
    result: 'saddle',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'carrot_on_a_stick',
    type: 'shaped',
    pattern: ['F ', ' C'],
    key: { 'F': 'fishing_rod', 'C': 'carrot' },
    result: 'carrot_on_a_stick',
    resultCount: 1,
    category: 'transportation',
  },

  // ===========================================================================
  // FOOD
  // ===========================================================================

  {
    id: 'bread',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'wheat' },
    result: 'bread',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'cake',
    type: 'shaped',
    pattern: ['MMM', 'SES', 'WWW'],
    key: { 'M': 'milk_bucket', 'S': 'sugar', 'E': 'egg', 'W': 'wheat' },
    result: 'cake',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'cookie',
    type: 'shaped',
    pattern: ['WCW'],
    key: { 'W': 'wheat', 'C': 'cocoa_beans' },
    result: 'cookie',
    resultCount: 8,
    category: 'food',
  },
  {
    id: 'pumpkin_pie',
    type: 'shapeless',
    ingredients: ['pumpkin', 'sugar', 'egg'],
    result: 'pumpkin_pie',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'golden_apple',
    type: 'shaped',
    pattern: ['GGG', 'GAG', 'GGG'],
    key: { 'G': 'gold_ingot', 'A': 'apple' },
    result: 'golden_apple',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'golden_carrot',
    type: 'shaped',
    pattern: ['GGG', 'GCG', 'GGG'],
    key: { 'G': 'gold_nugget', 'C': 'carrot' },
    result: 'golden_carrot',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'mushroom_stew',
    type: 'shapeless',
    ingredients: ['red_mushroom', 'brown_mushroom', 'bowl'],
    result: 'mushroom_stew',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'rabbit_stew',
    type: 'shaped',
    pattern: [' R ', 'CPM', ' B '],
    key: { 'R': 'cooked_rabbit', 'C': 'carrot', 'P': 'baked_potato', 'M': 'brown_mushroom', 'B': 'bowl' },
    result: 'rabbit_stew',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'beetroot_soup',
    type: 'shaped',
    pattern: ['BBB', 'BBB', ' O '],
    key: { 'B': 'beetroot', 'O': 'bowl' },
    result: 'beetroot_soup',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'sugar',
    type: 'shapeless',
    ingredients: ['sugar_cane'],
    result: 'sugar',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'melon_seeds',
    type: 'shapeless',
    ingredients: ['melon_slice'],
    result: 'melon_seeds',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'pumpkin_seeds',
    type: 'shapeless',
    ingredients: ['pumpkin'],
    result: 'pumpkin_seeds',
    resultCount: 4,
    category: 'food',
  },
  {
    id: 'melon_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'melon_slice' },
    result: 'melon_block',
    resultCount: 1,
    category: 'food',
  },
];
