// =============================================================================
// Minecraft: Nintendo Switch Edition — Building Blocks Recipes
// =============================================================================
// Slabs, stairs, fences, fence gates, doors, trapdoors, walls, brick-type
// blocks, sandstone variants, quartz variants, polished stone, mossy variants,
// glass panes, iron bars, miscellaneous building blocks, buttons, and
// pressure plates.
// =============================================================================

import type { CraftingRecipe } from '@/types/minecraft-switch';

export const BUILDING_RECIPES: CraftingRecipe[] = [

  // ===========================================================================
  // BUILDING BLOCKS
  // ===========================================================================

  // --- Slabs (6 each from 3 blocks) ---

  {
    id: 'oak_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'oak_planks' },
    result: 'oak_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'spruce_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'birch_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'birch_planks' },
    result: 'birch_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'jungle_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'acacia_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'dark_oak_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'stone' },
    result: 'stone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'cobblestone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'sandstone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'bricks' },
    result: 'brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'nether_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'quartz_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'quartz_block' },
    result: 'quartz_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'red_sandstone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'purpur_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'purpur_block' },
    result: 'purpur_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'prismarine_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'prismarine' },
    result: 'prismarine_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'prismarine_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'prismarine_bricks' },
    result: 'prismarine_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'dark_prismarine_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'dark_prismarine' },
    result: 'dark_prismarine_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'smooth_stone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'smooth_stone' },
    result: 'smooth_stone_slab',
    resultCount: 6,
    category: 'building',
  },

  // --- Stairs (4 each from 6 blocks) ---

  {
    id: 'oak_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'spruce_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'birch_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'birch_planks' },
    result: 'birch_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'jungle_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'acacia_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'dark_oak_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'cobblestone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'stone_brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'sandstone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'bricks' },
    result: 'brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'nether_brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'quartz_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'quartz_block' },
    result: 'quartz_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'red_sandstone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'purpur_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'purpur_block' },
    result: 'purpur_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'prismarine_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'prismarine' },
    result: 'prismarine_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'stone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'stone' },
    result: 'stone_stairs',
    resultCount: 4,
    category: 'building',
  },

  // --- Fences ---

  {
    id: 'oak_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'oak_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'spruce_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'spruce_planks', '|': 'stick' },
    result: 'spruce_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'birch_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'birch_planks', '|': 'stick' },
    result: 'birch_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'jungle_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'jungle_planks', '|': 'stick' },
    result: 'jungle_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'acacia_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'acacia_planks', '|': 'stick' },
    result: 'acacia_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'dark_oak_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'dark_oak_planks', '|': 'stick' },
    result: 'dark_oak_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'nether_brick_fence',
    type: 'shaped',
    pattern: ['#B#', '#B#'],
    key: { '#': 'nether_bricks', 'B': 'nether_brick' },
    result: 'nether_brick_fence',
    resultCount: 6,
    category: 'building',
  },

  // --- Fence Gates ---

  {
    id: 'oak_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'oak_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'spruce_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'spruce_planks', '|': 'stick' },
    result: 'spruce_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'birch_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'birch_planks', '|': 'stick' },
    result: 'birch_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'jungle_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'jungle_planks', '|': 'stick' },
    result: 'jungle_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'acacia_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'acacia_planks', '|': 'stick' },
    result: 'acacia_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'dark_oak_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'dark_oak_planks', '|': 'stick' },
    result: 'dark_oak_fence_gate',
    resultCount: 1,
    category: 'building',
  },

  // --- Doors ---

  {
    id: 'oak_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'oak_planks' },
    result: 'oak_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'spruce_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'birch_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'birch_planks' },
    result: 'birch_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'jungle_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'acacia_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'dark_oak_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'iron_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'iron_ingot' },
    result: 'iron_door',
    resultCount: 3,
    category: 'building',
  },

  // --- Trapdoors ---

  {
    id: 'oak_trapdoor',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_trapdoor',
    resultCount: 2,
    category: 'building',
  },
  {
    id: 'iron_trapdoor',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'iron_ingot' },
    result: 'iron_trapdoor',
    resultCount: 1,
    category: 'building',
  },

  // --- Walls ---

  {
    id: 'cobblestone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'mossy_cobblestone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'mossy_cobblestone' },
    result: 'mossy_cobblestone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'bricks' },
    result: 'brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'sandstone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'red_sandstone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'nether_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'end_stone_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'end_stone_bricks' },
    result: 'end_stone_brick_wall',
    resultCount: 6,
    category: 'building',
  },

  // --- Brick-type Blocks ---

  {
    id: 'bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'brick' },
    result: 'bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'stone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'stone' },
    result: 'stone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'nether_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'nether_brick' },
    result: 'nether_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'red_nether_bricks',
    type: 'shaped',
    pattern: ['NW', 'WN'],
    key: { 'N': 'nether_brick', 'W': 'nether_wart' },
    result: 'red_nether_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'end_stone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'end_stone' },
    result: 'end_stone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'prismarine',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'prismarine_shard' },
    result: 'prismarine',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'prismarine_bricks',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'prismarine_shard' },
    result: 'prismarine_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'dark_prismarine',
    type: 'shaped',
    pattern: ['SSS', 'SDS', 'SSS'],
    key: { 'S': 'prismarine_shard', 'D': 'black_dye' },
    result: 'dark_prismarine',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'sea_lantern',
    type: 'shaped',
    pattern: ['SCS', 'CCC', 'SCS'],
    key: { 'S': 'prismarine_shard', 'C': 'prismarine_crystals' },
    result: 'sea_lantern',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'purpur_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'popped_chorus_fruit' },
    result: 'purpur_block',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'purpur_pillar',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'purpur_slab' },
    result: 'purpur_pillar',
    resultCount: 1,
    category: 'building',
  },

  // --- Sandstone Variants ---

  {
    id: 'sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'sand' },
    result: 'sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'red_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'red_sand' },
    result: 'red_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_sandstone',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'sandstone_slab' },
    result: 'chiseled_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_red_sandstone',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'red_sandstone_slab' },
    result: 'chiseled_red_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'cut_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'sandstone' },
    result: 'cut_sandstone',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'cut_red_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'red_sandstone' },
    result: 'cut_red_sandstone',
    resultCount: 4,
    category: 'building',
  },

  // --- Quartz Variants ---

  {
    id: 'quartz_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'nether_quartz' },
    result: 'quartz_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_quartz',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'quartz_slab' },
    result: 'chiseled_quartz',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'quartz_pillar',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'quartz_block' },
    result: 'quartz_pillar',
    resultCount: 2,
    category: 'building',
  },

  // --- Polished Stone Variants ---

  {
    id: 'polished_granite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'granite' },
    result: 'polished_granite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_diorite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'diorite' },
    result: 'polished_diorite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_andesite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'andesite' },
    result: 'polished_andesite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_basalt',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'basalt' },
    result: 'polished_basalt',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_blackstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'blackstone' },
    result: 'polished_blackstone',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_blackstone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'polished_blackstone' },
    result: 'polished_blackstone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'chiseled_stone_bricks',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'stone_brick_slab' },
    result: 'chiseled_stone_bricks',
    resultCount: 1,
    category: 'building',
  },

  // --- Mossy Variants ---

  {
    id: 'mossy_cobblestone',
    type: 'shapeless',
    ingredients: ['cobblestone', 'vine'],
    result: 'mossy_cobblestone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'mossy_stone_bricks',
    type: 'shapeless',
    ingredients: ['stone_bricks', 'vine'],
    result: 'mossy_stone_bricks',
    resultCount: 1,
    category: 'building',
  },

  // --- Glass Pane ---

  {
    id: 'glass_pane',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'glass' },
    result: 'glass_pane',
    resultCount: 16,
    category: 'building',
  },
  {
    id: 'iron_bars',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'iron_ingot' },
    result: 'iron_bars',
    resultCount: 16,
    category: 'building',
  },

  // --- Miscellaneous Building Blocks ---

  {
    id: 'hay_bale',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'wheat' },
    result: 'hay_bale',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'bone_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'bone_meal' },
    result: 'bone_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'snow_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'snowball' },
    result: 'snow_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'packed_ice',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'ice' },
    result: 'packed_ice',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'blue_ice',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'packed_ice' },
    result: 'blue_ice',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'coarse_dirt',
    type: 'shaped',
    pattern: ['DG', 'GD'],
    key: { 'D': 'dirt', 'G': 'gravel' },
    result: 'coarse_dirt',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'dried_kelp_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'dried_kelp' },
    result: 'dried_kelp_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'honeycomb_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'honeycomb' },
    result: 'honeycomb_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'magma_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'magma_cream' },
    result: 'magma_block',
    resultCount: 1,
    category: 'building',
  },

  // --- Buttons ---

  {
    id: 'oak_button',
    type: 'shapeless',
    ingredients: ['oak_planks'],
    result: 'oak_button',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'stone_button',
    type: 'shapeless',
    ingredients: ['stone'],
    result: 'stone_button',
    resultCount: 1,
    category: 'redstone',
  },

  // --- Pressure Plates ---

  {
    id: 'oak_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'oak_planks' },
    result: 'oak_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'stone_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'stone' },
    result: 'stone_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'light_weighted_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'gold_ingot' },
    result: 'light_weighted_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'heavy_weighted_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'iron_ingot' },
    result: 'heavy_weighted_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
];
