// =============================================================================
// Minecraft: Nintendo Switch Edition — Misc, Dyes, Decoration & Smelting
// =============================================================================
// Mineral blocks (9-to-1 and 1-to-9 conversions), nuggets, netherite ingot,
// all 16 dyes, decoration items (bookshelf, ladder, signs, beds, carpets,
// banners, lanterns, campfires, etc.), shapeless crafting recipes (book, paper,
// fire charge, magma cream, etc.), and all smelting/cooking recipes.
// =============================================================================

import type { CraftingRecipe } from '@/types/minecraft-switch';

export const MISC_RECIPES: CraftingRecipe[] = [

  // ===========================================================================
  // MINERAL BLOCKS (9 ingots/gems -> 1 block)
  // ===========================================================================

  {
    id: 'coal_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'coal' },
    result: 'coal_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'iron_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'iron_ingot' },
    result: 'iron_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'gold_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'gold_ingot' },
    result: 'gold_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'diamond_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'diamond' },
    result: 'diamond_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'emerald_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'emerald' },
    result: 'emerald_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'lapis_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'lapis_lazuli' },
    result: 'lapis_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'redstone_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'redstone' },
    result: 'redstone_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'netherite_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'netherite_ingot' },
    result: 'netherite_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'copper_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'copper_ingot' },
    result: 'copper_block',
    resultCount: 1,
    category: 'building',
  },

  // --- Reverse: Block -> 9 ingots/gems ---

  {
    id: 'coal_from_block',
    type: 'shapeless',
    ingredients: ['coal_block'],
    result: 'coal',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'iron_ingot_from_block',
    type: 'shapeless',
    ingredients: ['iron_block'],
    result: 'iron_ingot',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'gold_ingot_from_block',
    type: 'shapeless',
    ingredients: ['gold_block'],
    result: 'gold_ingot',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'diamond_from_block',
    type: 'shapeless',
    ingredients: ['diamond_block'],
    result: 'diamond',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'emerald_from_block',
    type: 'shapeless',
    ingredients: ['emerald_block'],
    result: 'emerald',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'lapis_from_block',
    type: 'shapeless',
    ingredients: ['lapis_block'],
    result: 'lapis_lazuli',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'redstone_from_block',
    type: 'shapeless',
    ingredients: ['redstone_block'],
    result: 'redstone',
    resultCount: 9,
    category: 'misc',
  },

  // --- Nuggets ---

  {
    id: 'gold_nugget',
    type: 'shapeless',
    ingredients: ['gold_ingot'],
    result: 'gold_nugget',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'gold_ingot_from_nuggets',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'gold_nugget' },
    result: 'gold_ingot',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'iron_nugget',
    type: 'shapeless',
    ingredients: ['iron_ingot'],
    result: 'iron_nugget',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'iron_ingot_from_nuggets',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'iron_nugget' },
    result: 'iron_ingot',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'netherite_ingot',
    type: 'shaped',
    pattern: ['SSSS', 'GGGG'],
    key: { 'S': 'netherite_scrap', 'G': 'gold_ingot' },
    result: 'netherite_ingot',
    resultCount: 1,
    category: 'misc',
  },

  // ===========================================================================
  // DYES — All 16 colors
  // ===========================================================================

  {
    id: 'white_dye',
    type: 'shapeless',
    ingredients: ['bone_meal'],
    result: 'white_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'white_dye_from_lily',
    type: 'shapeless',
    ingredients: ['lily_of_the_valley'],
    result: 'white_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'orange_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'yellow_dye'],
    result: 'orange_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'orange_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['orange_tulip'],
    result: 'orange_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'magenta_dye',
    type: 'shapeless',
    ingredients: ['purple_dye', 'pink_dye'],
    result: 'magenta_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'magenta_dye_from_allium',
    type: 'shapeless',
    ingredients: ['allium'],
    result: 'magenta_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'light_blue_dye',
    type: 'shapeless',
    ingredients: ['blue_dye', 'white_dye'],
    result: 'light_blue_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_blue_dye_from_orchid',
    type: 'shapeless',
    ingredients: ['blue_orchid'],
    result: 'light_blue_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'yellow_dye',
    type: 'shapeless',
    ingredients: ['dandelion'],
    result: 'yellow_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'lime_dye',
    type: 'shapeless',
    ingredients: ['green_dye', 'white_dye'],
    result: 'lime_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'pink_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'white_dye'],
    result: 'pink_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'pink_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['pink_tulip'],
    result: 'pink_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'gray_dye',
    type: 'shapeless',
    ingredients: ['black_dye', 'white_dye'],
    result: 'gray_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_gray_dye',
    type: 'shapeless',
    ingredients: ['gray_dye', 'white_dye'],
    result: 'light_gray_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_gray_dye_from_daisy',
    type: 'shapeless',
    ingredients: ['oxeye_daisy'],
    result: 'light_gray_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'cyan_dye',
    type: 'shapeless',
    ingredients: ['blue_dye', 'green_dye'],
    result: 'cyan_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'purple_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'blue_dye'],
    result: 'purple_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'blue_dye',
    type: 'shapeless',
    ingredients: ['lapis_lazuli'],
    result: 'blue_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'brown_dye',
    type: 'shapeless',
    ingredients: ['cocoa_beans'],
    result: 'brown_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'green_dye',
    type: 'shapeless',
    ingredients: ['cactus_green'],
    result: 'green_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye',
    type: 'shapeless',
    ingredients: ['poppy'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['red_tulip'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye_from_beetroot',
    type: 'shapeless',
    ingredients: ['beetroot'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'black_dye',
    type: 'shapeless',
    ingredients: ['ink_sac'],
    result: 'black_dye',
    resultCount: 1,
    category: 'decoration',
  },

  // ===========================================================================
  // DECORATION & MISC
  // ===========================================================================

  {
    id: 'bookshelf',
    type: 'shaped',
    pattern: ['###', 'BBB', '###'],
    key: { '#': 'oak_planks', 'B': 'book' },
    result: 'bookshelf',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'ladder',
    type: 'shaped',
    pattern: ['| |', '|||', '| |'],
    key: { '|': 'stick' },
    result: 'ladder',
    resultCount: 3,
    category: 'decoration',
  },
  {
    id: 'sign',
    type: 'shaped',
    pattern: ['###', '###', ' | '],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'sign',
    resultCount: 3,
    category: 'decoration',
  },
  {
    id: 'painting',
    type: 'shaped',
    pattern: ['|||', '|W|', '|||'],
    key: { '|': 'stick', 'W': 'white_wool' },
    result: 'painting',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'item_frame',
    type: 'shaped',
    pattern: ['|||', '|L|', '|||'],
    key: { '|': 'stick', 'L': 'leather' },
    result: 'item_frame',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'flower_pot',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'brick' },
    result: 'flower_pot',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'armor_stand',
    type: 'shaped',
    pattern: ['|||', ' | ', '|S|'],
    key: { '|': 'stick', 'S': 'smooth_stone_slab' },
    result: 'armor_stand',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'lantern',
    type: 'shaped',
    pattern: ['III', 'ITI', 'III'],
    key: { 'I': 'iron_nugget', 'T': 'torch' },
    result: 'lantern',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_lantern',
    type: 'shaped',
    pattern: ['III', 'ITI', 'III'],
    key: { 'I': 'iron_nugget', 'T': 'soul_torch' },
    result: 'soul_lantern',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_torch',
    type: 'shaped',
    pattern: ['C', '|', 'S'],
    key: { 'C': 'coal', '|': 'stick', 'S': 'soul_sand' },
    result: 'soul_torch',
    resultCount: 4,
    category: 'decoration',
  },
  {
    id: 'end_rod',
    type: 'shaped',
    pattern: ['R', 'P'],
    key: { 'R': 'blaze_rod', 'P': 'popped_chorus_fruit' },
    result: 'end_rod',
    resultCount: 4,
    category: 'decoration',
  },
  {
    id: 'campfire',
    type: 'shaped',
    pattern: [' | ', '|C|', 'LLL'],
    key: { '|': 'stick', 'C': 'coal', 'L': 'oak_log' },
    result: 'campfire',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_campfire',
    type: 'shaped',
    pattern: [' | ', '|S|', 'LLL'],
    key: { '|': 'stick', 'S': 'soul_sand', 'L': 'oak_log' },
    result: 'soul_campfire',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'white_banner',
    type: 'shaped',
    pattern: ['###', '###', ' | '],
    key: { '#': 'white_wool', '|': 'stick' },
    result: 'white_banner',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'scaffolding',
    type: 'shaped',
    pattern: ['B|B', 'B B', 'B B'],
    key: { 'B': 'bamboo', '|': 'string' },
    result: 'scaffolding',
    resultCount: 6,
    category: 'decoration',
  },
  {
    id: 'chain',
    type: 'shaped',
    pattern: ['N', 'I', 'N'],
    key: { 'N': 'iron_nugget', 'I': 'iron_ingot' },
    result: 'chain',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Beds (all 16 colors, showing the primary white bed recipe + dyed variants) ---

  {
    id: 'white_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'white_wool', '#': 'oak_planks' },
    result: 'white_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'red_wool', '#': 'oak_planks' },
    result: 'red_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'blue_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'blue_wool', '#': 'oak_planks' },
    result: 'blue_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'green_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'green_wool', '#': 'oak_planks' },
    result: 'green_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'yellow_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'yellow_wool', '#': 'oak_planks' },
    result: 'yellow_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'black_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'black_wool', '#': 'oak_planks' },
    result: 'black_bed',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Carpets ---

  {
    id: 'white_carpet',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'white_wool' },
    result: 'white_carpet',
    resultCount: 3,
    category: 'decoration',
  },

  // --- Glass Panes (stained) ---

  {
    id: 'white_stained_glass_pane',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'white_stained_glass' },
    result: 'white_stained_glass_pane',
    resultCount: 16,
    category: 'decoration',
  },

  // --- Stained Glass (with dye) ---

  {
    id: 'white_stained_glass',
    type: 'shaped',
    pattern: ['###', '#D#', '###'],
    key: { '#': 'glass', 'D': 'white_dye' },
    result: 'white_stained_glass',
    resultCount: 8,
    category: 'decoration',
  },

  // --- Wool from string ---

  {
    id: 'white_wool',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'string' },
    result: 'white_wool',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Concrete Powder (sand + gravel + dye) ---

  {
    id: 'white_concrete_powder',
    type: 'shapeless',
    ingredients: ['white_dye', 'sand', 'sand', 'sand', 'sand', 'gravel', 'gravel', 'gravel', 'gravel'],
    result: 'white_concrete_powder',
    resultCount: 8,
    category: 'building',
  },

  // ===========================================================================
  // SHAPELESS CRAFTING RECIPES
  // ===========================================================================

  {
    id: 'book',
    type: 'shapeless',
    ingredients: ['paper', 'paper', 'paper', 'leather'],
    result: 'book',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'paper',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'sugar_cane' },
    result: 'paper',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'fire_charge',
    type: 'shapeless',
    ingredients: ['gunpowder', 'blaze_powder', 'coal'],
    result: 'fire_charge',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'magma_cream',
    type: 'shapeless',
    ingredients: ['slime_ball', 'blaze_powder'],
    result: 'magma_cream',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'fermented_spider_eye',
    type: 'shapeless',
    ingredients: ['spider_eye', 'brown_mushroom', 'sugar'],
    result: 'fermented_spider_eye',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'ender_eye',
    type: 'shapeless',
    ingredients: ['ender_pearl', 'blaze_powder'],
    result: 'ender_eye',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'blaze_powder',
    type: 'shapeless',
    ingredients: ['blaze_rod'],
    result: 'blaze_powder',
    resultCount: 2,
    category: 'misc',
  },
  {
    id: 'bone_meal',
    type: 'shapeless',
    ingredients: ['bone'],
    result: 'bone_meal',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'bowl',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'oak_planks' },
    result: 'bowl',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'bucket',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'iron_ingot' },
    result: 'bucket',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'map',
    type: 'shaped',
    pattern: ['PPP', 'PCP', 'PPP'],
    key: { 'P': 'paper', 'C': 'compass' },
    result: 'map',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'glass_bottle',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'glass' },
    result: 'glass_bottle',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'writable_book',
    type: 'shapeless',
    ingredients: ['book', 'ink_sac', 'feather'],
    result: 'writable_book',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'glowstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'glowstone_dust' },
    result: 'glowstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'beehive',
    type: 'shaped',
    pattern: ['###', 'HHH', '###'],
    key: { '#': 'oak_planks', 'H': 'honeycomb' },
    result: 'beehive',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'respawn_anchor',
    type: 'shaped',
    pattern: ['CCC', 'GGG', 'CCC'],
    key: { 'C': 'crying_obsidian', 'G': 'glowstone' },
    result: 'respawn_anchor',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'lodestone',
    type: 'shaped',
    pattern: ['SSS', 'SCS', 'SSS'],
    key: { 'S': 'chiseled_stone_bricks', 'C': 'netherite_ingot' },
    result: 'lodestone',
    resultCount: 1,
    category: 'misc',
  },

  // ===========================================================================
  // SMELTING RECIPES (bonus section - uses furnace/blast furnace/smoker)
  // ===========================================================================

  {
    id: 'smelt_iron_ore',
    type: 'smelting',
    input: 'raw_iron',
    result: 'iron_ingot',
    resultCount: 1,
    experience: 0.7,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_gold_ore',
    type: 'smelting',
    input: 'raw_gold',
    result: 'gold_ingot',
    resultCount: 1,
    experience: 1.0,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_copper_ore',
    type: 'smelting',
    input: 'raw_copper',
    result: 'copper_ingot',
    resultCount: 1,
    experience: 0.7,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_sand',
    type: 'smelting',
    input: 'sand',
    result: 'glass',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_cobblestone',
    type: 'smelting',
    input: 'cobblestone',
    result: 'stone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_stone',
    type: 'smelting',
    input: 'stone',
    result: 'smooth_stone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_sandstone',
    type: 'smelting',
    input: 'sandstone',
    result: 'smooth_sandstone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_clay',
    type: 'smelting',
    input: 'clay_ball',
    result: 'brick',
    resultCount: 1,
    experience: 0.3,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_netherrack',
    type: 'smelting',
    input: 'nether_brick_item',
    result: 'nether_brick',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_log',
    type: 'smelting',
    input: 'oak_log',
    result: 'charcoal',
    resultCount: 1,
    experience: 0.15,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_raw_beef',
    type: 'smelting',
    input: 'raw_beef',
    result: 'cooked_beef',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_porkchop',
    type: 'smelting',
    input: 'raw_porkchop',
    result: 'cooked_porkchop',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_chicken',
    type: 'smelting',
    input: 'raw_chicken',
    result: 'cooked_chicken',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_mutton',
    type: 'smelting',
    input: 'raw_mutton',
    result: 'cooked_mutton',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_rabbit',
    type: 'smelting',
    input: 'raw_rabbit',
    result: 'cooked_rabbit',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_cod',
    type: 'smelting',
    input: 'raw_cod',
    result: 'cooked_cod',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_salmon',
    type: 'smelting',
    input: 'raw_salmon',
    result: 'cooked_salmon',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_potato',
    type: 'smelting',
    input: 'potato',
    result: 'baked_potato',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_kelp',
    type: 'smelting',
    input: 'kelp',
    result: 'dried_kelp',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_ancient_debris',
    type: 'smelting',
    input: 'ancient_debris',
    result: 'netherite_scrap',
    resultCount: 1,
    experience: 2.0,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_chorus_fruit',
    type: 'smelting',
    input: 'chorus_fruit',
    result: 'popped_chorus_fruit',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_cactus',
    type: 'smelting',
    input: 'cactus',
    result: 'cactus_green',
    resultCount: 1,
    experience: 0.2,
    cookingTime: 200,
    category: 'decoration',
  },
  {
    id: 'smelt_wet_sponge',
    type: 'smelting',
    input: 'wet_sponge',
    result: 'sponge',
    resultCount: 1,
    experience: 0.15,
    cookingTime: 200,
    category: 'building',
  },
];
