// =============================================================================
// Minecraft: Nintendo Switch Edition — Complete Crafting Recipe Registry
// =============================================================================
// Defines 200+ crafting recipes covering all major Minecraft recipe categories:
// tools, weapons, armor, building blocks, functional blocks, redstone,
// transportation, food, dyes, decorations, mineral blocks, and more.
// Recipes use the shaped/shapeless format defined in CraftingRecipe from
// @/types/minecraft-switch.
// =============================================================================

import type { CraftingRecipe } from '@/types/minecraft-switch';

// =============================================================================
// RECIPE REGISTRY
// =============================================================================

export const RECIPES: CraftingRecipe[] = [

  // ===========================================================================
  // BASIC CRAFTING — Planks, Sticks, Fundamental Materials
  // ===========================================================================

  // --- Planks (from logs) — 6 wood types, each yields 4 planks ---

  {
    id: 'oak_planks',
    type: 'shapeless',
    ingredients: ['oak_log'],
    result: 'oak_planks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'spruce_planks',
    type: 'shapeless',
    ingredients: ['spruce_log'],
    result: 'spruce_planks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'birch_planks',
    type: 'shapeless',
    ingredients: ['birch_log'],
    result: 'birch_planks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'jungle_planks',
    type: 'shapeless',
    ingredients: ['jungle_log'],
    result: 'jungle_planks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'acacia_planks',
    type: 'shapeless',
    ingredients: ['acacia_log'],
    result: 'acacia_planks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'dark_oak_planks',
    type: 'shapeless',
    ingredients: ['dark_oak_log'],
    result: 'dark_oak_planks',
    resultCount: 4,
    category: 'building',
  },

  // --- Sticks ---

  {
    id: 'stick',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'oak_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'stick_from_spruce',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'spruce_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'stick_from_birch',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'birch_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'stick_from_jungle',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'jungle_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'stick_from_acacia',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'acacia_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'stick_from_dark_oak',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'dark_oak_planks' },
    result: 'stick',
    resultCount: 4,
    category: 'misc',
  },

  // --- Torches ---

  {
    id: 'torch',
    type: 'shaped',
    pattern: ['C', '|'],
    key: { 'C': 'coal', '|': 'stick' },
    result: 'torch',
    resultCount: 4,
    category: 'decoration',
  },
  {
    id: 'torch_from_charcoal',
    type: 'shaped',
    pattern: ['C', '|'],
    key: { 'C': 'charcoal', '|': 'stick' },
    result: 'torch',
    resultCount: 4,
    category: 'decoration',
  },

  // ===========================================================================
  // TOOLS — 5 tiers x 5 tool types = 25 recipes
  // ===========================================================================

  // --- Wooden Tools ---

  {
    id: 'wooden_pickaxe',
    type: 'shaped',
    pattern: ['###', ' | ', ' | '],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'wooden_pickaxe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'wooden_axe',
    type: 'shaped',
    pattern: ['##', '#|', ' |'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'wooden_axe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'wooden_shovel',
    type: 'shaped',
    pattern: ['#', '|', '|'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'wooden_shovel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'wooden_hoe',
    type: 'shaped',
    pattern: ['##', ' |', ' |'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'wooden_hoe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'wooden_sword',
    type: 'shaped',
    pattern: ['#', '#', '|'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'wooden_sword',
    resultCount: 1,
    category: 'combat',
  },

  // --- Stone Tools ---

  {
    id: 'stone_pickaxe',
    type: 'shaped',
    pattern: ['###', ' | ', ' | '],
    key: { '#': 'cobblestone', '|': 'stick' },
    result: 'stone_pickaxe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'stone_axe',
    type: 'shaped',
    pattern: ['##', '#|', ' |'],
    key: { '#': 'cobblestone', '|': 'stick' },
    result: 'stone_axe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'stone_shovel',
    type: 'shaped',
    pattern: ['#', '|', '|'],
    key: { '#': 'cobblestone', '|': 'stick' },
    result: 'stone_shovel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'stone_hoe',
    type: 'shaped',
    pattern: ['##', ' |', ' |'],
    key: { '#': 'cobblestone', '|': 'stick' },
    result: 'stone_hoe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'stone_sword',
    type: 'shaped',
    pattern: ['#', '#', '|'],
    key: { '#': 'cobblestone', '|': 'stick' },
    result: 'stone_sword',
    resultCount: 1,
    category: 'combat',
  },

  // --- Iron Tools ---

  {
    id: 'iron_pickaxe',
    type: 'shaped',
    pattern: ['###', ' | ', ' | '],
    key: { '#': 'iron_ingot', '|': 'stick' },
    result: 'iron_pickaxe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'iron_axe',
    type: 'shaped',
    pattern: ['##', '#|', ' |'],
    key: { '#': 'iron_ingot', '|': 'stick' },
    result: 'iron_axe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'iron_shovel',
    type: 'shaped',
    pattern: ['#', '|', '|'],
    key: { '#': 'iron_ingot', '|': 'stick' },
    result: 'iron_shovel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'iron_hoe',
    type: 'shaped',
    pattern: ['##', ' |', ' |'],
    key: { '#': 'iron_ingot', '|': 'stick' },
    result: 'iron_hoe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'iron_sword',
    type: 'shaped',
    pattern: ['#', '#', '|'],
    key: { '#': 'iron_ingot', '|': 'stick' },
    result: 'iron_sword',
    resultCount: 1,
    category: 'combat',
  },

  // --- Golden Tools ---

  {
    id: 'golden_pickaxe',
    type: 'shaped',
    pattern: ['###', ' | ', ' | '],
    key: { '#': 'gold_ingot', '|': 'stick' },
    result: 'golden_pickaxe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'golden_axe',
    type: 'shaped',
    pattern: ['##', '#|', ' |'],
    key: { '#': 'gold_ingot', '|': 'stick' },
    result: 'golden_axe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'golden_shovel',
    type: 'shaped',
    pattern: ['#', '|', '|'],
    key: { '#': 'gold_ingot', '|': 'stick' },
    result: 'golden_shovel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'golden_hoe',
    type: 'shaped',
    pattern: ['##', ' |', ' |'],
    key: { '#': 'gold_ingot', '|': 'stick' },
    result: 'golden_hoe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'golden_sword',
    type: 'shaped',
    pattern: ['#', '#', '|'],
    key: { '#': 'gold_ingot', '|': 'stick' },
    result: 'golden_sword',
    resultCount: 1,
    category: 'combat',
  },

  // --- Diamond Tools ---

  {
    id: 'diamond_pickaxe',
    type: 'shaped',
    pattern: ['###', ' | ', ' | '],
    key: { '#': 'diamond', '|': 'stick' },
    result: 'diamond_pickaxe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'diamond_axe',
    type: 'shaped',
    pattern: ['##', '#|', ' |'],
    key: { '#': 'diamond', '|': 'stick' },
    result: 'diamond_axe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'diamond_shovel',
    type: 'shaped',
    pattern: ['#', '|', '|'],
    key: { '#': 'diamond', '|': 'stick' },
    result: 'diamond_shovel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'diamond_hoe',
    type: 'shaped',
    pattern: ['##', ' |', ' |'],
    key: { '#': 'diamond', '|': 'stick' },
    result: 'diamond_hoe',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'diamond_sword',
    type: 'shaped',
    pattern: ['#', '#', '|'],
    key: { '#': 'diamond', '|': 'stick' },
    result: 'diamond_sword',
    resultCount: 1,
    category: 'combat',
  },

  // --- Other Tools ---

  {
    id: 'shears',
    type: 'shaped',
    pattern: [' #', '# '],
    key: { '#': 'iron_ingot' },
    result: 'shears',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'flint_and_steel',
    type: 'shaped',
    pattern: ['F ', ' I'],
    key: { 'F': 'flint', 'I': 'iron_ingot' },
    result: 'flint_and_steel',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'fishing_rod',
    type: 'shaped',
    pattern: ['  |', ' |S', '| S'],
    key: { '|': 'stick', 'S': 'string' },
    result: 'fishing_rod',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'compass',
    type: 'shaped',
    pattern: [' I ', 'IRI', ' I '],
    key: { 'I': 'iron_ingot', 'R': 'redstone' },
    result: 'compass',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'clock',
    type: 'shaped',
    pattern: [' G ', 'GRG', ' G '],
    key: { 'G': 'gold_ingot', 'R': 'redstone' },
    result: 'clock',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'spyglass',
    type: 'shaped',
    pattern: ['A', 'C', 'C'],
    key: { 'A': 'amethyst_shard', 'C': 'copper_ingot' },
    result: 'spyglass',
    resultCount: 1,
    category: 'tools',
  },
  {
    id: 'lead',
    type: 'shaped',
    pattern: ['SS ', 'SB ', '  S'],
    key: { 'S': 'string', 'B': 'slime_ball' },
    result: 'lead',
    resultCount: 2,
    category: 'tools',
  },

  // ===========================================================================
  // ARMOR — 4 tiers x 4 pieces = 16 recipes
  // ===========================================================================

  // --- Leather Armor ---

  {
    id: 'leather_helmet',
    type: 'shaped',
    pattern: ['###', '# #'],
    key: { '#': 'leather' },
    result: 'leather_helmet',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'leather_chestplate',
    type: 'shaped',
    pattern: ['# #', '###', '###'],
    key: { '#': 'leather' },
    result: 'leather_chestplate',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'leather_leggings',
    type: 'shaped',
    pattern: ['###', '# #', '# #'],
    key: { '#': 'leather' },
    result: 'leather_leggings',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'leather_boots',
    type: 'shaped',
    pattern: ['# #', '# #'],
    key: { '#': 'leather' },
    result: 'leather_boots',
    resultCount: 1,
    category: 'combat',
  },

  // --- Iron Armor ---

  {
    id: 'iron_helmet',
    type: 'shaped',
    pattern: ['###', '# #'],
    key: { '#': 'iron_ingot' },
    result: 'iron_helmet',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'iron_chestplate',
    type: 'shaped',
    pattern: ['# #', '###', '###'],
    key: { '#': 'iron_ingot' },
    result: 'iron_chestplate',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'iron_leggings',
    type: 'shaped',
    pattern: ['###', '# #', '# #'],
    key: { '#': 'iron_ingot' },
    result: 'iron_leggings',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'iron_boots',
    type: 'shaped',
    pattern: ['# #', '# #'],
    key: { '#': 'iron_ingot' },
    result: 'iron_boots',
    resultCount: 1,
    category: 'combat',
  },

  // --- Golden Armor ---

  {
    id: 'golden_helmet',
    type: 'shaped',
    pattern: ['###', '# #'],
    key: { '#': 'gold_ingot' },
    result: 'golden_helmet',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'golden_chestplate',
    type: 'shaped',
    pattern: ['# #', '###', '###'],
    key: { '#': 'gold_ingot' },
    result: 'golden_chestplate',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'golden_leggings',
    type: 'shaped',
    pattern: ['###', '# #', '# #'],
    key: { '#': 'gold_ingot' },
    result: 'golden_leggings',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'golden_boots',
    type: 'shaped',
    pattern: ['# #', '# #'],
    key: { '#': 'gold_ingot' },
    result: 'golden_boots',
    resultCount: 1,
    category: 'combat',
  },

  // --- Diamond Armor ---

  {
    id: 'diamond_helmet',
    type: 'shaped',
    pattern: ['###', '# #'],
    key: { '#': 'diamond' },
    result: 'diamond_helmet',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'diamond_chestplate',
    type: 'shaped',
    pattern: ['# #', '###', '###'],
    key: { '#': 'diamond' },
    result: 'diamond_chestplate',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'diamond_leggings',
    type: 'shaped',
    pattern: ['###', '# #', '# #'],
    key: { '#': 'diamond' },
    result: 'diamond_leggings',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'diamond_boots',
    type: 'shaped',
    pattern: ['# #', '# #'],
    key: { '#': 'diamond' },
    result: 'diamond_boots',
    resultCount: 1,
    category: 'combat',
  },

  // --- Other Combat Items ---

  {
    id: 'bow',
    type: 'shaped',
    pattern: [' |S', '| S', ' |S'],
    key: { '|': 'stick', 'S': 'string' },
    result: 'bow',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'arrow',
    type: 'shaped',
    pattern: ['F', '|', 'E'],
    key: { 'F': 'flint', '|': 'stick', 'E': 'feather' },
    result: 'arrow',
    resultCount: 4,
    category: 'combat',
  },
  {
    id: 'crossbow',
    type: 'shaped',
    pattern: ['|I|', 'STS', ' | '],
    key: { '|': 'stick', 'I': 'iron_ingot', 'S': 'string', 'T': 'tripwire_hook' },
    result: 'crossbow',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'shield',
    type: 'shaped',
    pattern: ['#I#', '###', ' # '],
    key: { '#': 'oak_planks', 'I': 'iron_ingot' },
    result: 'shield',
    resultCount: 1,
    category: 'combat',
  },
  {
    id: 'spectral_arrow',
    type: 'shaped',
    pattern: [' G ', 'GAG', ' G '],
    key: { 'G': 'glowstone_dust', 'A': 'arrow' },
    result: 'spectral_arrow',
    resultCount: 2,
    category: 'combat',
  },

  // ===========================================================================
  // BUILDING BLOCKS
  // ===========================================================================

  // --- Slabs (6 each from 3 blocks) ---

  {
    id: 'oak_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'oak_planks' },
    result: 'oak_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'spruce_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'birch_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'birch_planks' },
    result: 'birch_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'jungle_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'acacia_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'dark_oak_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'stone' },
    result: 'stone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'cobblestone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'sandstone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'bricks' },
    result: 'brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'nether_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'quartz_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'quartz_block' },
    result: 'quartz_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'red_sandstone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'purpur_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'purpur_block' },
    result: 'purpur_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'prismarine_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'prismarine' },
    result: 'prismarine_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'prismarine_brick_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'prismarine_bricks' },
    result: 'prismarine_brick_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'dark_prismarine_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'dark_prismarine' },
    result: 'dark_prismarine_slab',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'smooth_stone_slab',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'smooth_stone' },
    result: 'smooth_stone_slab',
    resultCount: 6,
    category: 'building',
  },

  // --- Stairs (4 each from 6 blocks) ---

  {
    id: 'oak_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'spruce_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'birch_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'birch_planks' },
    result: 'birch_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'jungle_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'acacia_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'dark_oak_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'cobblestone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'stone_brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'sandstone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'bricks' },
    result: 'brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'nether_brick_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'quartz_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'quartz_block' },
    result: 'quartz_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'red_sandstone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'purpur_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'purpur_block' },
    result: 'purpur_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'prismarine_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'prismarine' },
    result: 'prismarine_stairs',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'stone_stairs',
    type: 'shaped',
    pattern: ['#  ', '## ', '###'],
    key: { '#': 'stone' },
    result: 'stone_stairs',
    resultCount: 4,
    category: 'building',
  },

  // --- Fences ---

  {
    id: 'oak_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'oak_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'spruce_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'spruce_planks', '|': 'stick' },
    result: 'spruce_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'birch_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'birch_planks', '|': 'stick' },
    result: 'birch_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'jungle_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'jungle_planks', '|': 'stick' },
    result: 'jungle_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'acacia_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'acacia_planks', '|': 'stick' },
    result: 'acacia_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'dark_oak_fence',
    type: 'shaped',
    pattern: ['#|#', '#|#'],
    key: { '#': 'dark_oak_planks', '|': 'stick' },
    result: 'dark_oak_fence',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'nether_brick_fence',
    type: 'shaped',
    pattern: ['#B#', '#B#'],
    key: { '#': 'nether_bricks', 'B': 'nether_brick' },
    result: 'nether_brick_fence',
    resultCount: 6,
    category: 'building',
  },

  // --- Fence Gates ---

  {
    id: 'oak_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'oak_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'spruce_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'spruce_planks', '|': 'stick' },
    result: 'spruce_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'birch_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'birch_planks', '|': 'stick' },
    result: 'birch_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'jungle_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'jungle_planks', '|': 'stick' },
    result: 'jungle_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'acacia_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'acacia_planks', '|': 'stick' },
    result: 'acacia_fence_gate',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'dark_oak_fence_gate',
    type: 'shaped',
    pattern: ['|#|', '|#|'],
    key: { '#': 'dark_oak_planks', '|': 'stick' },
    result: 'dark_oak_fence_gate',
    resultCount: 1,
    category: 'building',
  },

  // --- Doors ---

  {
    id: 'oak_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'oak_planks' },
    result: 'oak_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'spruce_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'birch_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'birch_planks' },
    result: 'birch_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'jungle_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'acacia_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'dark_oak_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_door',
    resultCount: 3,
    category: 'building',
  },
  {
    id: 'iron_door',
    type: 'shaped',
    pattern: ['##', '##', '##'],
    key: { '#': 'iron_ingot' },
    result: 'iron_door',
    resultCount: 3,
    category: 'building',
  },

  // --- Trapdoors ---

  {
    id: 'oak_trapdoor',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_trapdoor',
    resultCount: 2,
    category: 'building',
  },
  {
    id: 'iron_trapdoor',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'iron_ingot' },
    result: 'iron_trapdoor',
    resultCount: 1,
    category: 'building',
  },

  // --- Walls ---

  {
    id: 'cobblestone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'cobblestone' },
    result: 'cobblestone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'mossy_cobblestone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'mossy_cobblestone' },
    result: 'mossy_cobblestone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'stone_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'stone_bricks' },
    result: 'stone_brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'bricks' },
    result: 'brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'sandstone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'sandstone' },
    result: 'sandstone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'red_sandstone_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'red_sandstone' },
    result: 'red_sandstone_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'nether_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'nether_bricks' },
    result: 'nether_brick_wall',
    resultCount: 6,
    category: 'building',
  },
  {
    id: 'end_stone_brick_wall',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'end_stone_bricks' },
    result: 'end_stone_brick_wall',
    resultCount: 6,
    category: 'building',
  },

  // --- Brick-type Blocks ---

  {
    id: 'bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'brick' },
    result: 'bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'stone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'stone' },
    result: 'stone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'nether_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'nether_brick' },
    result: 'nether_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'red_nether_bricks',
    type: 'shaped',
    pattern: ['NW', 'WN'],
    key: { 'N': 'nether_brick', 'W': 'nether_wart' },
    result: 'red_nether_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'end_stone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'end_stone' },
    result: 'end_stone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'prismarine',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'prismarine_shard' },
    result: 'prismarine',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'prismarine_bricks',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'prismarine_shard' },
    result: 'prismarine_bricks',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'dark_prismarine',
    type: 'shaped',
    pattern: ['SSS', 'SDS', 'SSS'],
    key: { 'S': 'prismarine_shard', 'D': 'black_dye' },
    result: 'dark_prismarine',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'sea_lantern',
    type: 'shaped',
    pattern: ['SCS', 'CCC', 'SCS'],
    key: { 'S': 'prismarine_shard', 'C': 'prismarine_crystals' },
    result: 'sea_lantern',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'purpur_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'popped_chorus_fruit' },
    result: 'purpur_block',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'purpur_pillar',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'purpur_slab' },
    result: 'purpur_pillar',
    resultCount: 1,
    category: 'building',
  },

  // --- Sandstone Variants ---

  {
    id: 'sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'sand' },
    result: 'sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'red_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'red_sand' },
    result: 'red_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_sandstone',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'sandstone_slab' },
    result: 'chiseled_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_red_sandstone',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'red_sandstone_slab' },
    result: 'chiseled_red_sandstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'cut_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'sandstone' },
    result: 'cut_sandstone',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'cut_red_sandstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'red_sandstone' },
    result: 'cut_red_sandstone',
    resultCount: 4,
    category: 'building',
  },

  // --- Quartz Variants ---

  {
    id: 'quartz_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'nether_quartz' },
    result: 'quartz_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'chiseled_quartz',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'quartz_slab' },
    result: 'chiseled_quartz',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'quartz_pillar',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'quartz_block' },
    result: 'quartz_pillar',
    resultCount: 2,
    category: 'building',
  },

  // --- Polished Stone Variants ---

  {
    id: 'polished_granite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'granite' },
    result: 'polished_granite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_diorite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'diorite' },
    result: 'polished_diorite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_andesite',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'andesite' },
    result: 'polished_andesite',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_basalt',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'basalt' },
    result: 'polished_basalt',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_blackstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'blackstone' },
    result: 'polished_blackstone',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'polished_blackstone_bricks',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'polished_blackstone' },
    result: 'polished_blackstone_bricks',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'chiseled_stone_bricks',
    type: 'shaped',
    pattern: ['#', '#'],
    key: { '#': 'stone_brick_slab' },
    result: 'chiseled_stone_bricks',
    resultCount: 1,
    category: 'building',
  },

  // --- Mossy Variants ---

  {
    id: 'mossy_cobblestone',
    type: 'shapeless',
    ingredients: ['cobblestone', 'vine'],
    result: 'mossy_cobblestone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'mossy_stone_bricks',
    type: 'shapeless',
    ingredients: ['stone_bricks', 'vine'],
    result: 'mossy_stone_bricks',
    resultCount: 1,
    category: 'building',
  },

  // --- Glass Pane ---

  {
    id: 'glass_pane',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'glass' },
    result: 'glass_pane',
    resultCount: 16,
    category: 'building',
  },
  {
    id: 'iron_bars',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'iron_ingot' },
    result: 'iron_bars',
    resultCount: 16,
    category: 'building',
  },

  // --- Miscellaneous Building Blocks ---

  {
    id: 'hay_bale',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'wheat' },
    result: 'hay_bale',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'bone_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'bone_meal' },
    result: 'bone_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'snow_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'snowball' },
    result: 'snow_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'packed_ice',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'ice' },
    result: 'packed_ice',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'blue_ice',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'packed_ice' },
    result: 'blue_ice',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'coarse_dirt',
    type: 'shaped',
    pattern: ['DG', 'GD'],
    key: { 'D': 'dirt', 'G': 'gravel' },
    result: 'coarse_dirt',
    resultCount: 4,
    category: 'building',
  },
  {
    id: 'dried_kelp_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'dried_kelp' },
    result: 'dried_kelp_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'honeycomb_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'honeycomb' },
    result: 'honeycomb_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'magma_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'magma_cream' },
    result: 'magma_block',
    resultCount: 1,
    category: 'building',
  },

  // --- Buttons ---

  {
    id: 'oak_button',
    type: 'shapeless',
    ingredients: ['oak_planks'],
    result: 'oak_button',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'stone_button',
    type: 'shapeless',
    ingredients: ['stone'],
    result: 'stone_button',
    resultCount: 1,
    category: 'redstone',
  },

  // --- Pressure Plates ---

  {
    id: 'oak_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'oak_planks' },
    result: 'oak_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'stone_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'stone' },
    result: 'stone_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'light_weighted_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'gold_ingot' },
    result: 'light_weighted_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'heavy_weighted_pressure_plate',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'iron_ingot' },
    result: 'heavy_weighted_pressure_plate',
    resultCount: 1,
    category: 'redstone',
  },

  // ===========================================================================
  // FUNCTIONAL BLOCKS
  // ===========================================================================

  {
    id: 'crafting_table',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'oak_planks' },
    result: 'crafting_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'furnace',
    type: 'shaped',
    pattern: ['###', '# #', '###'],
    key: { '#': 'cobblestone' },
    result: 'furnace',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'blast_furnace',
    type: 'shaped',
    pattern: ['III', 'IFI', 'SSS'],
    key: { 'I': 'iron_ingot', 'F': 'furnace', 'S': 'smooth_stone' },
    result: 'blast_furnace',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'smoker',
    type: 'shaped',
    pattern: [' L ', 'LFL', ' L '],
    key: { 'L': 'oak_log', 'F': 'furnace' },
    result: 'smoker',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'chest',
    type: 'shaped',
    pattern: ['###', '# #', '###'],
    key: { '#': 'oak_planks' },
    result: 'chest',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'trapped_chest',
    type: 'shapeless',
    ingredients: ['chest', 'tripwire_hook'],
    result: 'trapped_chest',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'ender_chest',
    type: 'shaped',
    pattern: ['OOO', 'OEO', 'OOO'],
    key: { 'O': 'obsidian', 'E': 'ender_eye' },
    result: 'ender_chest',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'barrel',
    type: 'shaped',
    pattern: ['#S#', '# #', '#S#'],
    key: { '#': 'oak_planks', 'S': 'oak_slab' },
    result: 'barrel',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'enchanting_table',
    type: 'shaped',
    pattern: [' B ', 'DOD', 'OOO'],
    key: { 'B': 'book', 'D': 'diamond', 'O': 'obsidian' },
    result: 'enchanting_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'brewing_stand',
    type: 'shaped',
    pattern: [' R ', 'SSS'],
    key: { 'R': 'blaze_rod', 'S': 'cobblestone' },
    result: 'brewing_stand',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'anvil',
    type: 'shaped',
    pattern: ['BBB', ' I ', 'III'],
    key: { 'B': 'iron_block', 'I': 'iron_ingot' },
    result: 'anvil',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'beacon',
    type: 'shaped',
    pattern: ['GGG', 'GNG', 'OOO'],
    key: { 'G': 'glass', 'N': 'nether_star', 'O': 'obsidian' },
    result: 'beacon',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'grindstone',
    type: 'shaped',
    pattern: ['|S|', '# #'],
    key: { '|': 'stick', 'S': 'stone_slab', '#': 'oak_planks' },
    result: 'grindstone',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'stonecutter',
    type: 'shaped',
    pattern: [' I ', 'SSS'],
    key: { 'I': 'iron_ingot', 'S': 'stone' },
    result: 'stonecutter',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'loom',
    type: 'shaped',
    pattern: ['SS', '##'],
    key: { 'S': 'string', '#': 'oak_planks' },
    result: 'loom',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'cartography_table',
    type: 'shaped',
    pattern: ['PP', '##', '##'],
    key: { 'P': 'paper', '#': 'oak_planks' },
    result: 'cartography_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'fletching_table',
    type: 'shaped',
    pattern: ['FF', '##', '##'],
    key: { 'F': 'flint', '#': 'oak_planks' },
    result: 'fletching_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'smithing_table',
    type: 'shaped',
    pattern: ['II', '##', '##'],
    key: { 'I': 'iron_ingot', '#': 'oak_planks' },
    result: 'smithing_table',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'composter',
    type: 'shaped',
    pattern: ['# #', '# #', '###'],
    key: { '#': 'oak_slab' },
    result: 'composter',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'cauldron',
    type: 'shaped',
    pattern: ['# #', '# #', '###'],
    key: { '#': 'iron_ingot' },
    result: 'cauldron',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'jukebox',
    type: 'shaped',
    pattern: ['###', '#D#', '###'],
    key: { '#': 'oak_planks', 'D': 'diamond' },
    result: 'jukebox',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'note_block',
    type: 'shaped',
    pattern: ['###', '#R#', '###'],
    key: { '#': 'oak_planks', 'R': 'redstone' },
    result: 'note_block',
    resultCount: 1,
    category: 'redstone',
  },

  // ===========================================================================
  // REDSTONE
  // ===========================================================================

  {
    id: 'redstone_torch',
    type: 'shaped',
    pattern: ['R', '|'],
    key: { 'R': 'redstone', '|': 'stick' },
    result: 'redstone_torch',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_repeater',
    type: 'shaped',
    pattern: ['TRT', 'SSS'],
    key: { 'T': 'redstone_torch', 'R': 'redstone', 'S': 'stone' },
    result: 'redstone_repeater',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_comparator',
    type: 'shaped',
    pattern: [' T ', 'TQT', 'SSS'],
    key: { 'T': 'redstone_torch', 'Q': 'nether_quartz', 'S': 'stone' },
    result: 'redstone_comparator',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'piston',
    type: 'shaped',
    pattern: ['###', 'CIC', 'CRC'],
    key: { '#': 'oak_planks', 'C': 'cobblestone', 'I': 'iron_ingot', 'R': 'redstone' },
    result: 'piston',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'sticky_piston',
    type: 'shaped',
    pattern: ['S', 'P'],
    key: { 'S': 'slime_ball', 'P': 'piston' },
    result: 'sticky_piston',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'observer',
    type: 'shaped',
    pattern: ['CCC', 'RRQ', 'CCC'],
    key: { 'C': 'cobblestone', 'R': 'redstone', 'Q': 'nether_quartz' },
    result: 'observer',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'dropper',
    type: 'shaped',
    pattern: ['CCC', 'C C', 'CRC'],
    key: { 'C': 'cobblestone', 'R': 'redstone' },
    result: 'dropper',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'dispenser',
    type: 'shaped',
    pattern: ['CCC', 'CBC', 'CRC'],
    key: { 'C': 'cobblestone', 'B': 'bow', 'R': 'redstone' },
    result: 'dispenser',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'hopper',
    type: 'shaped',
    pattern: ['I I', 'ICI', ' I '],
    key: { 'I': 'iron_ingot', 'C': 'chest' },
    result: 'hopper',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'tnt',
    type: 'shaped',
    pattern: ['GSG', 'SGS', 'GSG'],
    key: { 'G': 'gunpowder', 'S': 'sand' },
    result: 'tnt',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'tripwire_hook',
    type: 'shaped',
    pattern: ['I', '|', '#'],
    key: { 'I': 'iron_ingot', '|': 'stick', '#': 'oak_planks' },
    result: 'tripwire_hook',
    resultCount: 2,
    category: 'redstone',
  },
  {
    id: 'target',
    type: 'shaped',
    pattern: [' R ', 'RHR', ' R '],
    key: { 'R': 'redstone', 'H': 'hay_bale' },
    result: 'target',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'lever',
    type: 'shaped',
    pattern: ['|', '#'],
    key: { '|': 'stick', '#': 'cobblestone' },
    result: 'lever',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'daylight_detector',
    type: 'shaped',
    pattern: ['GGG', 'QQQ', 'SSS'],
    key: { 'G': 'glass', 'Q': 'nether_quartz', 'S': 'oak_slab' },
    result: 'daylight_detector',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'redstone_lamp',
    type: 'shaped',
    pattern: [' R ', 'RGR', ' R '],
    key: { 'R': 'redstone', 'G': 'glowstone' },
    result: 'redstone_lamp',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'slime_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'slime_ball' },
    result: 'slime_block',
    resultCount: 1,
    category: 'redstone',
  },
  {
    id: 'honey_block',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'honey_bottle' },
    result: 'honey_block',
    resultCount: 1,
    category: 'redstone',
  },

  // ===========================================================================
  // TRANSPORTATION
  // ===========================================================================

  {
    id: 'rail',
    type: 'shaped',
    pattern: ['I I', 'I|I', 'I I'],
    key: { 'I': 'iron_ingot', '|': 'stick' },
    result: 'rail',
    resultCount: 16,
    category: 'transportation',
  },
  {
    id: 'powered_rail',
    type: 'shaped',
    pattern: ['G G', 'G|G', 'GRG'],
    key: { 'G': 'gold_ingot', '|': 'stick', 'R': 'redstone' },
    result: 'powered_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'detector_rail',
    type: 'shaped',
    pattern: ['I I', 'ISI', 'IRI'],
    key: { 'I': 'iron_ingot', 'S': 'stone_pressure_plate', 'R': 'redstone' },
    result: 'detector_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'activator_rail',
    type: 'shaped',
    pattern: ['ISI', 'I|I', 'ISI'],
    key: { 'I': 'iron_ingot', 'S': 'stick', '|': 'redstone_torch' },
    result: 'activator_rail',
    resultCount: 6,
    category: 'transportation',
  },
  {
    id: 'minecart',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'iron_ingot' },
    result: 'minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'chest_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'chest'],
    result: 'chest_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'furnace_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'furnace'],
    result: 'furnace_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'hopper_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'hopper'],
    result: 'hopper_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'tnt_minecart',
    type: 'shapeless',
    ingredients: ['minecart', 'tnt'],
    result: 'tnt_minecart',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'oak_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'oak_planks' },
    result: 'oak_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'spruce_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'spruce_planks' },
    result: 'spruce_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'birch_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'birch_planks' },
    result: 'birch_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'jungle_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'jungle_planks' },
    result: 'jungle_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'acacia_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'acacia_planks' },
    result: 'acacia_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'dark_oak_boat',
    type: 'shaped',
    pattern: ['# #', '###'],
    key: { '#': 'dark_oak_planks' },
    result: 'dark_oak_boat',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'saddle_from_leather',
    type: 'shaped',
    pattern: ['LLL', 'L L'],
    key: { 'L': 'leather' },
    result: 'saddle',
    resultCount: 1,
    category: 'transportation',
  },
  {
    id: 'carrot_on_a_stick',
    type: 'shaped',
    pattern: ['F ', ' C'],
    key: { 'F': 'fishing_rod', 'C': 'carrot' },
    result: 'carrot_on_a_stick',
    resultCount: 1,
    category: 'transportation',
  },

  // ===========================================================================
  // FOOD
  // ===========================================================================

  {
    id: 'bread',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'wheat' },
    result: 'bread',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'cake',
    type: 'shaped',
    pattern: ['MMM', 'SES', 'WWW'],
    key: { 'M': 'milk_bucket', 'S': 'sugar', 'E': 'egg', 'W': 'wheat' },
    result: 'cake',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'cookie',
    type: 'shaped',
    pattern: ['WCW'],
    key: { 'W': 'wheat', 'C': 'cocoa_beans' },
    result: 'cookie',
    resultCount: 8,
    category: 'food',
  },
  {
    id: 'pumpkin_pie',
    type: 'shapeless',
    ingredients: ['pumpkin', 'sugar', 'egg'],
    result: 'pumpkin_pie',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'golden_apple',
    type: 'shaped',
    pattern: ['GGG', 'GAG', 'GGG'],
    key: { 'G': 'gold_ingot', 'A': 'apple' },
    result: 'golden_apple',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'golden_carrot',
    type: 'shaped',
    pattern: ['GGG', 'GCG', 'GGG'],
    key: { 'G': 'gold_nugget', 'C': 'carrot' },
    result: 'golden_carrot',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'mushroom_stew',
    type: 'shapeless',
    ingredients: ['red_mushroom', 'brown_mushroom', 'bowl'],
    result: 'mushroom_stew',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'rabbit_stew',
    type: 'shaped',
    pattern: [' R ', 'CPM', ' B '],
    key: { 'R': 'cooked_rabbit', 'C': 'carrot', 'P': 'baked_potato', 'M': 'brown_mushroom', 'B': 'bowl' },
    result: 'rabbit_stew',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'beetroot_soup',
    type: 'shaped',
    pattern: ['BBB', 'BBB', ' O '],
    key: { 'B': 'beetroot', 'O': 'bowl' },
    result: 'beetroot_soup',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'sugar',
    type: 'shapeless',
    ingredients: ['sugar_cane'],
    result: 'sugar',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'melon_seeds',
    type: 'shapeless',
    ingredients: ['melon_slice'],
    result: 'melon_seeds',
    resultCount: 1,
    category: 'food',
  },
  {
    id: 'pumpkin_seeds',
    type: 'shapeless',
    ingredients: ['pumpkin'],
    result: 'pumpkin_seeds',
    resultCount: 4,
    category: 'food',
  },
  {
    id: 'melon_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'melon_slice' },
    result: 'melon_block',
    resultCount: 1,
    category: 'food',
  },

  // ===========================================================================
  // MINERAL BLOCKS (9 ingots/gems -> 1 block)
  // ===========================================================================

  {
    id: 'coal_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'coal' },
    result: 'coal_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'iron_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'iron_ingot' },
    result: 'iron_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'gold_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'gold_ingot' },
    result: 'gold_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'diamond_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'diamond' },
    result: 'diamond_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'emerald_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'emerald' },
    result: 'emerald_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'lapis_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'lapis_lazuli' },
    result: 'lapis_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'redstone_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'redstone' },
    result: 'redstone_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'netherite_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'netherite_ingot' },
    result: 'netherite_block',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'copper_block',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'copper_ingot' },
    result: 'copper_block',
    resultCount: 1,
    category: 'building',
  },

  // --- Reverse: Block -> 9 ingots/gems ---

  {
    id: 'coal_from_block',
    type: 'shapeless',
    ingredients: ['coal_block'],
    result: 'coal',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'iron_ingot_from_block',
    type: 'shapeless',
    ingredients: ['iron_block'],
    result: 'iron_ingot',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'gold_ingot_from_block',
    type: 'shapeless',
    ingredients: ['gold_block'],
    result: 'gold_ingot',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'diamond_from_block',
    type: 'shapeless',
    ingredients: ['diamond_block'],
    result: 'diamond',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'emerald_from_block',
    type: 'shapeless',
    ingredients: ['emerald_block'],
    result: 'emerald',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'lapis_from_block',
    type: 'shapeless',
    ingredients: ['lapis_block'],
    result: 'lapis_lazuli',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'redstone_from_block',
    type: 'shapeless',
    ingredients: ['redstone_block'],
    result: 'redstone',
    resultCount: 9,
    category: 'misc',
  },

  // --- Nuggets ---

  {
    id: 'gold_nugget',
    type: 'shapeless',
    ingredients: ['gold_ingot'],
    result: 'gold_nugget',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'gold_ingot_from_nuggets',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'gold_nugget' },
    result: 'gold_ingot',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'iron_nugget',
    type: 'shapeless',
    ingredients: ['iron_ingot'],
    result: 'iron_nugget',
    resultCount: 9,
    category: 'misc',
  },
  {
    id: 'iron_ingot_from_nuggets',
    type: 'shaped',
    pattern: ['###', '###', '###'],
    key: { '#': 'iron_nugget' },
    result: 'iron_ingot',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'netherite_ingot',
    type: 'shaped',
    pattern: ['SSSS', 'GGGG'],
    key: { 'S': 'netherite_scrap', 'G': 'gold_ingot' },
    result: 'netherite_ingot',
    resultCount: 1,
    category: 'misc',
  },

  // ===========================================================================
  // DYES — All 16 colors
  // ===========================================================================

  {
    id: 'white_dye',
    type: 'shapeless',
    ingredients: ['bone_meal'],
    result: 'white_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'white_dye_from_lily',
    type: 'shapeless',
    ingredients: ['lily_of_the_valley'],
    result: 'white_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'orange_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'yellow_dye'],
    result: 'orange_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'orange_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['orange_tulip'],
    result: 'orange_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'magenta_dye',
    type: 'shapeless',
    ingredients: ['purple_dye', 'pink_dye'],
    result: 'magenta_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'magenta_dye_from_allium',
    type: 'shapeless',
    ingredients: ['allium'],
    result: 'magenta_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'light_blue_dye',
    type: 'shapeless',
    ingredients: ['blue_dye', 'white_dye'],
    result: 'light_blue_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_blue_dye_from_orchid',
    type: 'shapeless',
    ingredients: ['blue_orchid'],
    result: 'light_blue_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'yellow_dye',
    type: 'shapeless',
    ingredients: ['dandelion'],
    result: 'yellow_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'lime_dye',
    type: 'shapeless',
    ingredients: ['green_dye', 'white_dye'],
    result: 'lime_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'pink_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'white_dye'],
    result: 'pink_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'pink_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['pink_tulip'],
    result: 'pink_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'gray_dye',
    type: 'shapeless',
    ingredients: ['black_dye', 'white_dye'],
    result: 'gray_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_gray_dye',
    type: 'shapeless',
    ingredients: ['gray_dye', 'white_dye'],
    result: 'light_gray_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'light_gray_dye_from_daisy',
    type: 'shapeless',
    ingredients: ['oxeye_daisy'],
    result: 'light_gray_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'cyan_dye',
    type: 'shapeless',
    ingredients: ['blue_dye', 'green_dye'],
    result: 'cyan_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'purple_dye',
    type: 'shapeless',
    ingredients: ['red_dye', 'blue_dye'],
    result: 'purple_dye',
    resultCount: 2,
    category: 'decoration',
  },
  {
    id: 'blue_dye',
    type: 'shapeless',
    ingredients: ['lapis_lazuli'],
    result: 'blue_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'brown_dye',
    type: 'shapeless',
    ingredients: ['cocoa_beans'],
    result: 'brown_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'green_dye',
    type: 'shapeless',
    ingredients: ['cactus_green'],
    result: 'green_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye',
    type: 'shapeless',
    ingredients: ['poppy'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye_from_tulip',
    type: 'shapeless',
    ingredients: ['red_tulip'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_dye_from_beetroot',
    type: 'shapeless',
    ingredients: ['beetroot'],
    result: 'red_dye',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'black_dye',
    type: 'shapeless',
    ingredients: ['ink_sac'],
    result: 'black_dye',
    resultCount: 1,
    category: 'decoration',
  },

  // ===========================================================================
  // DECORATION & MISC
  // ===========================================================================

  {
    id: 'bookshelf',
    type: 'shaped',
    pattern: ['###', 'BBB', '###'],
    key: { '#': 'oak_planks', 'B': 'book' },
    result: 'bookshelf',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'ladder',
    type: 'shaped',
    pattern: ['| |', '|||', '| |'],
    key: { '|': 'stick' },
    result: 'ladder',
    resultCount: 3,
    category: 'decoration',
  },
  {
    id: 'sign',
    type: 'shaped',
    pattern: ['###', '###', ' | '],
    key: { '#': 'oak_planks', '|': 'stick' },
    result: 'sign',
    resultCount: 3,
    category: 'decoration',
  },
  {
    id: 'painting',
    type: 'shaped',
    pattern: ['|||', '|W|', '|||'],
    key: { '|': 'stick', 'W': 'white_wool' },
    result: 'painting',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'item_frame',
    type: 'shaped',
    pattern: ['|||', '|L|', '|||'],
    key: { '|': 'stick', 'L': 'leather' },
    result: 'item_frame',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'flower_pot',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'brick' },
    result: 'flower_pot',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'armor_stand',
    type: 'shaped',
    pattern: ['|||', ' | ', '|S|'],
    key: { '|': 'stick', 'S': 'smooth_stone_slab' },
    result: 'armor_stand',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'lantern',
    type: 'shaped',
    pattern: ['III', 'ITI', 'III'],
    key: { 'I': 'iron_nugget', 'T': 'torch' },
    result: 'lantern',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_lantern',
    type: 'shaped',
    pattern: ['III', 'ITI', 'III'],
    key: { 'I': 'iron_nugget', 'T': 'soul_torch' },
    result: 'soul_lantern',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_torch',
    type: 'shaped',
    pattern: ['C', '|', 'S'],
    key: { 'C': 'coal', '|': 'stick', 'S': 'soul_sand' },
    result: 'soul_torch',
    resultCount: 4,
    category: 'decoration',
  },
  {
    id: 'end_rod',
    type: 'shaped',
    pattern: ['R', 'P'],
    key: { 'R': 'blaze_rod', 'P': 'popped_chorus_fruit' },
    result: 'end_rod',
    resultCount: 4,
    category: 'decoration',
  },
  {
    id: 'campfire',
    type: 'shaped',
    pattern: [' | ', '|C|', 'LLL'],
    key: { '|': 'stick', 'C': 'coal', 'L': 'oak_log' },
    result: 'campfire',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'soul_campfire',
    type: 'shaped',
    pattern: [' | ', '|S|', 'LLL'],
    key: { '|': 'stick', 'S': 'soul_sand', 'L': 'oak_log' },
    result: 'soul_campfire',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'white_banner',
    type: 'shaped',
    pattern: ['###', '###', ' | '],
    key: { '#': 'white_wool', '|': 'stick' },
    result: 'white_banner',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'scaffolding',
    type: 'shaped',
    pattern: ['B|B', 'B B', 'B B'],
    key: { 'B': 'bamboo', '|': 'string' },
    result: 'scaffolding',
    resultCount: 6,
    category: 'decoration',
  },
  {
    id: 'chain',
    type: 'shaped',
    pattern: ['N', 'I', 'N'],
    key: { 'N': 'iron_nugget', 'I': 'iron_ingot' },
    result: 'chain',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Beds (all 16 colors, showing the primary white bed recipe + dyed variants) ---

  {
    id: 'white_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'white_wool', '#': 'oak_planks' },
    result: 'white_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'red_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'red_wool', '#': 'oak_planks' },
    result: 'red_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'blue_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'blue_wool', '#': 'oak_planks' },
    result: 'blue_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'green_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'green_wool', '#': 'oak_planks' },
    result: 'green_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'yellow_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'yellow_wool', '#': 'oak_planks' },
    result: 'yellow_bed',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'black_bed',
    type: 'shaped',
    pattern: ['WWW', '###'],
    key: { 'W': 'black_wool', '#': 'oak_planks' },
    result: 'black_bed',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Carpets ---

  {
    id: 'white_carpet',
    type: 'shaped',
    pattern: ['##'],
    key: { '#': 'white_wool' },
    result: 'white_carpet',
    resultCount: 3,
    category: 'decoration',
  },

  // --- Glass Panes (stained) ---

  {
    id: 'white_stained_glass_pane',
    type: 'shaped',
    pattern: ['###', '###'],
    key: { '#': 'white_stained_glass' },
    result: 'white_stained_glass_pane',
    resultCount: 16,
    category: 'decoration',
  },

  // --- Stained Glass (with dye) ---

  {
    id: 'white_stained_glass',
    type: 'shaped',
    pattern: ['###', '#D#', '###'],
    key: { '#': 'glass', 'D': 'white_dye' },
    result: 'white_stained_glass',
    resultCount: 8,
    category: 'decoration',
  },

  // --- Wool from string ---

  {
    id: 'white_wool',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'string' },
    result: 'white_wool',
    resultCount: 1,
    category: 'decoration',
  },

  // --- Concrete Powder (sand + gravel + dye) ---

  {
    id: 'white_concrete_powder',
    type: 'shapeless',
    ingredients: ['white_dye', 'sand', 'sand', 'sand', 'sand', 'gravel', 'gravel', 'gravel', 'gravel'],
    result: 'white_concrete_powder',
    resultCount: 8,
    category: 'building',
  },

  // ===========================================================================
  // SHAPELESS CRAFTING RECIPES
  // ===========================================================================

  {
    id: 'book',
    type: 'shapeless',
    ingredients: ['paper', 'paper', 'paper', 'leather'],
    result: 'book',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'paper',
    type: 'shaped',
    pattern: ['###'],
    key: { '#': 'sugar_cane' },
    result: 'paper',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'fire_charge',
    type: 'shapeless',
    ingredients: ['gunpowder', 'blaze_powder', 'coal'],
    result: 'fire_charge',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'magma_cream',
    type: 'shapeless',
    ingredients: ['slime_ball', 'blaze_powder'],
    result: 'magma_cream',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'fermented_spider_eye',
    type: 'shapeless',
    ingredients: ['spider_eye', 'brown_mushroom', 'sugar'],
    result: 'fermented_spider_eye',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'ender_eye',
    type: 'shapeless',
    ingredients: ['ender_pearl', 'blaze_powder'],
    result: 'ender_eye',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'blaze_powder',
    type: 'shapeless',
    ingredients: ['blaze_rod'],
    result: 'blaze_powder',
    resultCount: 2,
    category: 'misc',
  },
  {
    id: 'bone_meal',
    type: 'shapeless',
    ingredients: ['bone'],
    result: 'bone_meal',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'bowl',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'oak_planks' },
    result: 'bowl',
    resultCount: 4,
    category: 'misc',
  },
  {
    id: 'bucket',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'iron_ingot' },
    result: 'bucket',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'map',
    type: 'shaped',
    pattern: ['PPP', 'PCP', 'PPP'],
    key: { 'P': 'paper', 'C': 'compass' },
    result: 'map',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'glass_bottle',
    type: 'shaped',
    pattern: ['# #', ' # '],
    key: { '#': 'glass' },
    result: 'glass_bottle',
    resultCount: 3,
    category: 'misc',
  },
  {
    id: 'writable_book',
    type: 'shapeless',
    ingredients: ['book', 'ink_sac', 'feather'],
    result: 'writable_book',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'glowstone',
    type: 'shaped',
    pattern: ['##', '##'],
    key: { '#': 'glowstone_dust' },
    result: 'glowstone',
    resultCount: 1,
    category: 'building',
  },
  {
    id: 'beehive',
    type: 'shaped',
    pattern: ['###', 'HHH', '###'],
    key: { '#': 'oak_planks', 'H': 'honeycomb' },
    result: 'beehive',
    resultCount: 1,
    category: 'decoration',
  },
  {
    id: 'respawn_anchor',
    type: 'shaped',
    pattern: ['CCC', 'GGG', 'CCC'],
    key: { 'C': 'crying_obsidian', 'G': 'glowstone' },
    result: 'respawn_anchor',
    resultCount: 1,
    category: 'misc',
  },
  {
    id: 'lodestone',
    type: 'shaped',
    pattern: ['SSS', 'SCS', 'SSS'],
    key: { 'S': 'chiseled_stone_bricks', 'C': 'netherite_ingot' },
    result: 'lodestone',
    resultCount: 1,
    category: 'misc',
  },

  // ===========================================================================
  // SMELTING RECIPES (bonus section - uses furnace/blast furnace/smoker)
  // ===========================================================================

  {
    id: 'smelt_iron_ore',
    type: 'smelting',
    input: 'raw_iron',
    result: 'iron_ingot',
    resultCount: 1,
    experience: 0.7,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_gold_ore',
    type: 'smelting',
    input: 'raw_gold',
    result: 'gold_ingot',
    resultCount: 1,
    experience: 1.0,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_copper_ore',
    type: 'smelting',
    input: 'raw_copper',
    result: 'copper_ingot',
    resultCount: 1,
    experience: 0.7,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_sand',
    type: 'smelting',
    input: 'sand',
    result: 'glass',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_cobblestone',
    type: 'smelting',
    input: 'cobblestone',
    result: 'stone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_stone',
    type: 'smelting',
    input: 'stone',
    result: 'smooth_stone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_sandstone',
    type: 'smelting',
    input: 'sandstone',
    result: 'smooth_sandstone',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'building',
  },
  {
    id: 'smelt_clay',
    type: 'smelting',
    input: 'clay_ball',
    result: 'brick',
    resultCount: 1,
    experience: 0.3,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_netherrack',
    type: 'smelting',
    input: 'nether_brick_item',
    result: 'nether_brick',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_log',
    type: 'smelting',
    input: 'oak_log',
    result: 'charcoal',
    resultCount: 1,
    experience: 0.15,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_raw_beef',
    type: 'smelting',
    input: 'raw_beef',
    result: 'cooked_beef',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_porkchop',
    type: 'smelting',
    input: 'raw_porkchop',
    result: 'cooked_porkchop',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_chicken',
    type: 'smelting',
    input: 'raw_chicken',
    result: 'cooked_chicken',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_mutton',
    type: 'smelting',
    input: 'raw_mutton',
    result: 'cooked_mutton',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_rabbit',
    type: 'smelting',
    input: 'raw_rabbit',
    result: 'cooked_rabbit',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_cod',
    type: 'smelting',
    input: 'raw_cod',
    result: 'cooked_cod',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_raw_salmon',
    type: 'smelting',
    input: 'raw_salmon',
    result: 'cooked_salmon',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_potato',
    type: 'smelting',
    input: 'potato',
    result: 'baked_potato',
    resultCount: 1,
    experience: 0.35,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_kelp',
    type: 'smelting',
    input: 'kelp',
    result: 'dried_kelp',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'food',
  },
  {
    id: 'smelt_ancient_debris',
    type: 'smelting',
    input: 'ancient_debris',
    result: 'netherite_scrap',
    resultCount: 1,
    experience: 2.0,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_chorus_fruit',
    type: 'smelting',
    input: 'chorus_fruit',
    result: 'popped_chorus_fruit',
    resultCount: 1,
    experience: 0.1,
    cookingTime: 200,
    category: 'misc',
  },
  {
    id: 'smelt_cactus',
    type: 'smelting',
    input: 'cactus',
    result: 'cactus_green',
    resultCount: 1,
    experience: 0.2,
    cookingTime: 200,
    category: 'decoration',
  },
  {
    id: 'smelt_wet_sponge',
    type: 'smelting',
    input: 'wet_sponge',
    result: 'sponge',
    resultCount: 1,
    experience: 0.15,
    cookingTime: 200,
    category: 'building',
  },
];

// =============================================================================
// CATEGORY CONSTANTS
// =============================================================================

export const RECIPE_CATEGORIES = [
  'all',
  'building',
  'decoration',
  'redstone',
  'transportation',
  'tools',
  'combat',
  'food',
  'misc',
] as const;

export type RecipeCategory = (typeof RECIPE_CATEGORIES)[number];

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Filter recipes by category. Returns all recipes if category is 'all'.
 * Only returns shaped and shapeless recipes (not smelting) by default.
 */
export function getRecipesByCategory(category: RecipeCategory, includeSmelting = false): CraftingRecipe[] {
  const filtered = includeSmelting
    ? RECIPES
    : RECIPES.filter(r => r.type === 'shaped' || r.type === 'shapeless');

  if (category === 'all') return filtered;
  return filtered.filter(r => r.category === category);
}

/**
 * Find a recipe by its unique ID.
 */
export function getRecipeById(id: string): CraftingRecipe | undefined {
  return RECIPES.find(r => r.id === id);
}

/**
 * Get all unique categories that have at least one recipe.
 */
export function getActiveCategories(): string[] {
  const cats = new Set(RECIPES.map(r => r.category));
  return Array.from(cats).sort();
}

/**
 * Get only crafting table recipes (shaped + shapeless, not smelting).
 */
export function getCraftingTableRecipes(): CraftingRecipe[] {
  return RECIPES.filter(r => r.type === 'shaped' || r.type === 'shapeless');
}

/**
 * Get only smelting recipes.
 */
export function getSmeltingRecipes(): CraftingRecipe[] {
  return RECIPES.filter(r => r.type === 'smelting');
}
